### ISSUE TITLE
Socks version error on Ubuntu after running under a LAN with proxy

### ISSUE THREAD

**Issue by urwithajit9** [egbertbouman/youtube-comment-downloader#1]
Hi,

After running the code, I am getting below error.

ajit@ajit-desktop:~/Downloads/youtube-comment-downloader-master$ python downloader.py --youtubeid YykjpeuMNEk --output comments
Downloading Youtube comments for video: YykjpeuMNEk
Error: Unable to determine SOCKS version from socks://10.10.80.11:3128/

Can you please, tell what is wrong in running the code.

Thanking You.

With Regards.

**Comment by egbertbouman** [comment]
Looks like this has to do with requests (see https://github.com/kennethreitz/requests/issues/3523). Not sure how to fix this, other than just bypassing the proxy.
