### ISSUE TITLE
YouTube's New "Paid-Comment-Chip"

### ISSUE THREAD

**Issue by d0tN3t** [egbertbouman/youtube-comment-downloader#100]
I just noticed YouTube has added a badge for paid comments. Anyway of extracting this as well?

https://www.youtube.com/watch?v=9SmWpqbV9KA&ab_channel=GamersNexus
![Screen Shot 2022-03-06 at 10 57 07 PM](https://user-images.githubusercontent.com/11362484/156970929-01ec3f41-6185-4eb1-9eb3-3ffce21953ac.png)

**Comment by ikkysleepy** [comment]
You can add this line:

`                           'paid_amount': comment['paidCommentChipRenderer']['pdgCommentChipRenderer']['chipText'].get('simpleText','0') if 'paidCommentChipRenderer' in comment else 0,
`

**Comment by egbertbouman** [comment]
Thanks! I've just updated the script to include this.
