### ISSUE TITLE
[BUG] dateparser.parse doesn't work for some languages

### ISSUE THREAD

**Issue by minamotorin** [egbertbouman/youtube-comment-downloader#101]
# Issue description

After https://github.com/egbertbouman/youtube-comment-downloader/commit/87c4f908b5c6cc0610c4d708cf5aa2b7a851d066, sometimes `'NoneType' object has no attribute 'timestamp'` occur for some languages.

```
> youtube-comment-downloader --youtubeid _LHnduxb0YQ -o test.json --language en
Downloading Youtube comments for video: _LHnduxb0YQ
Downloaded 415 comment(s)
[44.13 seconds] Done!
>
> youtube-comment-downloader --youtubeid _LHnduxb0YQ -o test.json --language ar
Downloading Youtube comments for video: _LHnduxb0YQ
Error: 'NoneType' object has no attribute 'timestamp'
>
> youtube-comment-downloader --youtubeid _LHnduxb0YQ -o test.json --language zh
Downloading Youtube comments for video: _LHnduxb0YQ
Error: 'NoneType' object has no attribute 'timestamp'
```

The following minimal code will help understanding  what is  wrong.

```python3
import dateparser
dateparser.parse('1个月前（修改过）'.split('(')[0].strip()).timestamp()
dateparser.parse('قبل 3 أسابيع'.split('(')[0].strip()).timestamp()
```

# Environments

- dateparser: 1.1.0
- youtube-comment-downloader: [5c45d9a](https://github.com/egbertbouman/youtube-comment-downloader/tree/5c45d9ac8e5804e504a72a0aa25b5e5f951c1de9)

Thanks.

**Comment by egbertbouman** [comment]
Thanks for letting me know! I guess the best way to deal with this is to just ignore the error and move on. It should work now.

**Comment by minamotorin** [comment]
Thanks for fixing!
