### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by ediowar** [egbertbouman/youtube-comment-downloader#103]
![Screenshot_2022-03-14_15-38-22](https://user-images.githubusercontent.com/44164186/158207607-1f3d4f22-dd1f-4d6a-98dc-ead9b3388f56.png)
https://youtu.be/SGbhc4Xy8rQ
youtube-comment-downloader https://github.com/egbertbouman/youtube-comment-downloader/commit/a86c25d30e0b7a9ad86fd992fc21edc44f99f36d
python3-dateparser 1.0.0-1
OS version: Debian 11.2

**Comment by egbertbouman** [comment]
I moved some code around recently.  If you run `__main__.py` instead of `downloader.py`, it should work.

Besides running from source, you can also install from PyPI (`pip install youtube-comment-downloader`), and then run using `youtube-comment-downloader`.
