### ISSUE TITLE
Code stops running

### ISSUE THREAD

**Issue by ntdas** [egbertbouman/youtube-comment-downloader#104]
Hi,
I used this command a few days ago, and it worked just fine. But today it was giving back error (looks like json error to me"

`youtube-comment-downloader --youtubeid "Cj0Tzu7duAE" --output "sample.json"`

Output
`Downloading Youtube comments for Cj0Tzu7duAE
Error: Expecting value: line 1 column 1 (char 0)`

**Comment by egbertbouman** [comment]
Looks like you're not getting a valid response. This is usually the case when Youtube is blocking you.
