### ISSUE TITLE
'Failed to set sorting' error

### ISSUE THREAD

**Issue by raelb** [egbertbouman/youtube-comment-downloader#105]
Hi,
I run the following command line:
> youtube-comment-downloader --youtubeid YTbCpfFlNAo --output YTbCpfFlNAo.json --sort 1

On second run, I get this error:
![image](https://user-images.githubusercontent.com/13108198/165000209-c5faaa8f-0207-42c9-b4c8-ac231d3a0c5c.png)

It seems to be because of existing ouput file, since If i delete the output file then it will run again without error.

**Comment by egbertbouman** [comment]
It seems to be working fine for me. Are you sure you're running the latest version?
You can upgrade using `pip install youtube-comment-downloader -U`.

**Comment by raelb** [comment]
Yes, I am using latest version (0.1.60). After further testing I see it does not depend on existence of output file. The error occurs intermittently.

https://user-images.githubusercontent.com/13108198/165090943-9bbfdb0d-4377-46ad-91b0-ffdd9e4b4a7d.mp4

Perhaps related to #93

**Comment by raelb** [comment]
I did a bit more investigation.

On some occasions the response does not contain any `sortMenu` key (see attached sample), so the reported error is correct. From my side i can try again or run with sort set to 0 (which will not run the sorting code block), which will always succeed.

By the way on some occasions the "action" json contains the key `engagement-panel-comments-section` in stead of `comments-section`, so this line of code will work in both cases:

> if (action['targetId'] == 'comments-section' or action['targetId'] == 'engagement-panel-comments-section'):
                      
Attached are some sample responses
[sample responses.zip](https://github.com/egbertbouman/youtube-comment-downloader/files/8585155/sample.responses.zip)

From my side you can close the issue

**Comment by egbertbouman** [comment]
Thanks for investigating this! I tried to reproduce the issue a couple of days ago, but couldn't.

When I have some time I'll try again and see if I can find a workaround in case the sortmenu is missing.

**Comment by mazayomaza** [comment]
I'm experiencing the same problem. I hope this problem gets addressed as soon as possible

**Comment by raelb** [comment]
As I say in previous comment, I do not think this can be resolved, since in some cases the required sort info is not available in the json response. What happens if you set sort to 0, i.e. `--sort 0`? It should always work.

**Comment by mazayomaza** [comment]
the sort 0 option does work but I did want to use the other option. thank you

**Comment by ujifgc** [comment]
Same issue here. On some old videos with just one comment the script can fail 20 times, then on 21st will work randomly.

Setting `--sort=0` always works

**Comment by qboriskr** [comment]
With option --sort=0 utility returns less comments than expected, for example only 20 of 1000.

**Comment by estebanpdl** [comment]
I have been facing the same issue here. While `--sort=0` worked well (when `--sort=1` fails) I only received up to 20 comments. The video has more than 1,000. I included the `limit` flag (`youtube-comment-downloader --youtubeid JwjwnSdI4Yw -o ./data/data2.json -s 0 -l 5000`), but still got only 20 commnets.

Thanks so much in advanced. Such a great tool.
