### ISSUE TITLE
Only downloads 1 comment

### ISSUE THREAD

**Issue by raelb** [egbertbouman/youtube-comment-downloader#106]
I'm quite sure the problem here is on my side and not to do with your script.
I'm trying to create my own script based on your `__init__.py` so that I can add some modifications to the source code and see the results.
My file is called `run.py`, so I will call `python run.py` to run it.
When called only 1 comment is downloaded. Can you help me understand why this is happening?

run.py is included in the zip
[test.zip](https://github.com/egbertbouman/youtube-comment-downloader/files/8550688/test.zip)

**Comment by egbertbouman** [comment]
Not sure why you've set the limit to -1. If you want  to download all comments you should set it to 0.

**Comment by raelb** [comment]
Sorry, silly mistake on my side. Thanks for pointing out
