### ISSUE TITLE
It's nice script.

### ISSUE THREAD

**Issue by ghost** [egbertbouman/youtube-comment-downloader#11]
First of all thanks you for the script. I come here from github search. Is there anyway I can return the result from a method instead of returning it in a file.

**Comment by egbertbouman** [comment]
Just in case anyone else is wondering about the same thing, please look at the `main` function for an example of how to use the `download_comments` function:
https://github.com/egbertbouman/youtube-comment-downloader/blob/56bcde42d313495bb15843fad828155fa5dd6e24/downloader.py#L233
