### ISSUE TITLE
limit isn't working

### ISSUE THREAD

**Issue by kdh8219** [egbertbouman/youtube-comment-downloader#110]
```
python .\downloader.py --youtubeid hGpcArsHex0 --output hGpcArsHex0.json --sort 0 --limit 493     
```
```
Downloading Youtube comments for video: ScMzIvxBSi4
Downloaded 20 comment(s)
[0.83 seconds] Done!
```
https://youtu.be/hGpcArsHex0

Even though I annotated lines 183 and 184 to release the limit, I still download only 20.   
Perhaps the structure of YouTube has changed.

**Comment by kdh8219** [comment]
I guess it's because I used the old version! But how do you use the new version? The structure has changed a lot

**Comment by egbertbouman** [comment]
You're right, the new version shouldn't have these problems. The easiest way to use the script is by following the instructions from README.md. If you prefer to run it from source, just run `python __main__.py`.
