### ISSUE TITLE
shorts - Error: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by pavo976** [egbertbouman/youtube-comment-downloader#118]
Hello. 
I try to get comments from "shorts", but get error:

```bash
youtube-comment-downloader --url https://youtube.com/shorts/NC4G_WnuKYs --output ./comments.json
```

Output:

```output
Downloading Youtube comments for https://youtube.com/shorts/NC4G_WnuKYs
Error: Expecting value: line 1 column 1 (char 0)
```

version:
```bash
youtube-comment-downloader==0.1.61
```

**Comment by egbertbouman** [comment]
Thanks for reporting!

I just fixed this in 0.1.63. If you're still having issues, please let me know.

**Comment by pavo976** [comment]
@egbertbouman - Thanks for the quick response and quick resolution.

**Comment by MathiasExorde** [comment]
Hello, the same problem is back, on last version.
Is it just me?

**Comment by egbertbouman** [comment]
@MathiasExorde It's not just you. I've just published a new release (0.1.70) and things should be working again.

**Comment by MathiasExorde** [comment]
Great, thanks.

**Comment by drattar** [comment]
also, this error "Error: Expecting value: line 1 column 1 (char 0)" in 2026.
