### ISSUE TITLE
Adding Comments Likes 

### ISSUE THREAD

**Issue by Mrs-Hudson** [egbertbouman/youtube-comment-downloader#12]
Hi
Awesome script! How would the CSS selector look if I were to add one for extracting the number of likes?

**Comment by d0tN3t** [comment]
Maybe something like this under like-counts?
It can be found here [https://github.com/egbertbouman/youtube-comment-downloader/pull/7/files](url)

+def extract_comments(html):
+    tree = lxml.html.fromstring(html)
+    item_sel = CSSSelector('.comment-item')
+    text_sel = CSSSelector('.comment-text-content')
+    time_sel = CSSSelector('.time')
+    author_sel = CSSSelector('.user-name')
+    vote_sel = CSSSelector('.like-count')

**Comment by d0tN3t** [comment]
I'm sorry, I might not understand fully what you mean. Do you mean find a CSSSelector for an "Input" like "textbox-input" or how to find all the CSSSelectors?

**Comment by egbertbouman** [comment]
This is now supported by default.
