### ISSUE TITLE
pip is pip3 with brew.sh on macOS

### ISSUE THREAD

**Issue by superbonaci** [egbertbouman/youtube-comment-downloader#125]
Installed `python` from brew.sh:
```
% brew install python
% brew postinstall python
```
However to install this package the command must be:
```
% pip3 install youtube-comment-downloader
```
Could you update the `README.md`?

**Comment by superbonaci** [comment]
It cannot use pip does not work. Maybe you are using older macOS version?

**Comment by superbonaci** [comment]
do not stale.

**Comment by superbonaci** [comment]
do not stale.

**Comment by superbonaci** [comment]
do not stale

**Comment by superbonaci** [comment]
do not stale

**Comment by superbonaci** [comment]
do not stale

**Comment by biggestsonicfan** [comment]
`pip` vs `pip3` are equivalent in the fact that both are pip. It's very much equivalent to your platform you are installing on handles, and it feels like this issue is out of scope of the actual project itself. The initial change to `pip3` was to differentiate the difference between a `pip` installation that was using Python 2.x, but this is no longer the case. Depending on the platform installation Win/Linux/Mac etc..., `pip` or `pip3` can be put into your path. Sometimes it's both. In fact, on Windows, the equivalent is usually `py -3.13 -m pip` where `3.13` is the version of python you wish to use with `pip`.

**Comment by superbonaci** [comment]
I'm just asking to add it to the README not to change any code.

**Comment by biggestsonicfan** [comment]
I didn't mention any changes to code. I simply said `pip3` and `pip` are the same thing. Usually linked to eachother.

If you read the README, the instructions state "Preferably inside a [python virtual environment](https://virtualenv.pypa.io/en/latest/) install this package via:"

The instructions are 100% correct for the virtual environment, and even include a link on instructions for how to use a virtual environment on your platform.

Also, if we are going by official standards here, the use of `pip3` is incorrect regardless. See the [Getting Started - Installing a Package](https://pip.pypa.io/en/stable/getting-started/#install-a-package) section of the official Pip documentation and you will see that for Mac the official command to install with is `python -m pip install sampleproject`. Adding incorrect information to the README isn't helpful.

EDIT: I failed to realize, but this specific issue is for brew.

This is a Pip module. As such the ability to install and use pip is documentation which falls outside the scope of documentation of the module itself. One example is given for a virtual environment, but yes using pip via brew will result in different instructions. It is assumed that if you decide to deviate from the given readme instructions, that will be up to the user to do their due diligence to make the module work.

There are various distributions of linux which prefer pip be installed as a package than python itself, but this too falls outside the scope of a pip module's readme. In fact, [the official module's page, which hosts information generated by pypi.org themselves](https://pypi.org/project/youtube-comment-downloader/) generate the command of `pip install youtube-comment-downloader`.

It's not pip modules are attempting to deceive users on the installation process, it's just due diligence for users on how to interpret said instructions for their own needs, such as using python3 through a brew installation, is required in these types of situations.

**Comment by superbonaci** [comment]
It's python's fault.
