### ISSUE TITLE
Error: Failed to set sorting when downloading community comments 

### ISSUE THREAD

**Issue by kellersefi** [egbertbouman/youtube-comment-downloader#128]
Following up on #102 

The following command runs successfully:
```
youtube-comment-downloader --url https://www.youtube.com/post/Ugkx2meuOt7vCSaQP4QsS5v4v-VG5WnVb7RU --output output.json
```

But this command returns an error:
```
youtube-comment-downloader --url https://www.youtube.com/post/Ugkx2meuOt7vCSaQP4QsS5v4v-VG5WnVb7RU --output output.json
```

The error is:
```
Error: Failed to set sorting
```

I tried community comments from different channels and the error reproduced every time.

**Comment by egbertbouman** [comment]
Sorry for the late response. Downloading communnity posts should be working again.
