### ISSUE TITLE
Script Hangs On Uploads That Were Live

### ISSUE THREAD

**Issue by d0tN3t** [egbertbouman/youtube-comment-downloader#13]
So I recently discovered a strange issue. When channel uploads a video that used to be live (not while it is live, but after) the script hangs. I can't quite figure out what changed. There are clearly existing comments, but the script is unable to grab them. 

Here is a video example:
https://www.youtube.com/watch?v=zCgDnMhd4yA

Could it possibly have something to do with the page_tokens? The initial top section of the download_comments function works, and I can get a printout, but once it jumps into the while page_token loop, I can no longer get a return from a standard "print()" method.

Any guesses?

**Comment by githb123** [comment]
It's the same for me. I view the comments through www.youtubextras.com/watch?v=ID. This site also doesn't show comments on videos that are uploads of live feeds. It's probably something on the youtube end.

As I see the author didn't ackowledge any of the open issues so the project is probably yet another internet dead code with no hope for fixes :(

**Comment by egbertbouman** [comment]
@githb123 You're right, I'm not actively maintaining this script. Sorry about that!

Since it looks like some people still find it useful, I've taken a look at this issue. It turns out that the problem is that youtube-comment-downloader uses an older API that allows you to download *all* comments. Unfortunately, it looks like this older API does not work for live feeds.

When I have some time I will add support for the newer API in case of live streams. This means that you won't have all comments for live streams, but at least you'll have some.

**Comment by egbertbouman** [comment]
Getting comments from live streams should now be supported. If it's still not working, feel free to reopen.

**Comment by d0tN3t** [comment]
Hey! I'm really glad you're back! Your script actually inspired me a lot to write up many other scripts to scrape YT...captions, entire channel libraries, user subscription, user playlist. The list goes on and on. So you were a huge inspiration in doing what I did. 
So when I discovered this problem back in 2018 I figured you'd given up so I managed to solve it. See I tried your code up against this video_id "xwt2-N2JqYc" and you can see the difference.

![image](https://user-images.githubusercontent.com/11362484/74114773-aaf82c00-4b71-11ea-8fe2-3c831947749e.png)

![image](https://user-images.githubusercontent.com/11362484/74114829-edba0400-4b71-11ea-9dd7-a811095b5f8d.png)

**Comment by d0tN3t** [comment]
Live printout
![image](https://user-images.githubusercontent.com/11362484/74115101-18f12300-4b73-11ea-879b-ebb858d8de82.png)

**Comment by egbertbouman** [comment]
Wow, thanks! Great to hear you like my script. When I wrote it I was just helping out a collegue who needed to crawl youtube comments for his research. After that, I haven't really looked at it anymore. I was a bit surprised to see that people still used it, I figured I should try to maintain it a bit more.

Anyway, I just fixed that bug you mentioned. Thanks for letting me know!

**Comment by d0tN3t** [comment]
So fixing the bug you just uploaded gets me 282 out of 301 comments, while my version gets me 291 out of 301. Maybe you can look at my version and see where we're both going wrong. and then you can host it on your GitHub (I'm more of a forker than a hoster lol). Anyway like I said you're the main inspiration for it. So it's really more your work than mine.

`from __future__ import print_function

import os
import sys
import time
import json
import requests
import argparse
import lxml.html

from lxml.cssselect import CSSSelector
from datetime import timedelta

# python downloader2.py -y zCgDnMhd4yA -o _deleteMe.json

YOUTUBE_COMMENTS_URL = 'https://www.youtube.com/watch?v={youtube_id}'
YOUTUBE_COMMENTS_AJAX_URL = 'https://www.youtube.com/comment_service_ajax'

USER_AGENT = 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36'




def find_value(html, key, num_chars=2, divider='"'):
    pos_begin = html.find(key) + len(key) + num_chars
    pos_end = html.find(divider, pos_begin)
    return html[pos_begin: pos_end]


def extract_comments(comments):
    for comment in comments:
        item = comment['commentThreadRenderer']['comment']['commentRenderer']
        contentText = item['contentText']

        try:
            text = contentText['simpleText']
        except:
            runs = contentText['runs']
            text = ''
            for run in runs:
                text += run['text']        

        try:
            replies = comment['commentThreadRenderer']['replies']['commentRepliesRenderer']['continuations'][0]['nextContinuationData']
        except:
            replies = False
        
        yield {
            'comment': {
                'cid': item['commentId'],
                'text': text,
                'time': item['publishedTimeText']['runs'][0]['text'],
                'author': item['authorText']['simpleText'],
                'authorid': item['authorEndpoint']['browseEndpoint']['browseId'],
                'likes': item['likeCount']
            },
            'replies': replies
        }



def ajax_request(session, url, params, data, retries=10, sleep=20):
    for _ in range(retries):
        response = session.post(url, params=params, data=data)
        if response.status_code == 200:
            response_dict = json.loads(response.text)
            return response_dict
        else:
            time.sleep(sleep)


def download_comments(youtube_id, sleep=1):
    threshold = 1
    session = requests.Session()
    session.headers['User-Agent'] = USER_AGENT

    # Get Youtube page with initial comments
    url = YOUTUBE_COMMENTS_URL.format(youtube_id=youtube_id)
    response = session.get(url)
    html = response.text

    page_token = True
    session_token = find_value(html, 'XSRF_TOKEN', 4)
    comment_token = find_value(html, 'COMMENTS_TOKEN', 4)
    itct = find_value(html, 'itct', 3)
    client_name = find_value(html, 'INNERTUBE_CONTEXT_CLIENT_NAME', 2, ',')
    client_version = find_value(html, 'INNERTUBE_CONTEXT_CLIENT_VERSION', 3)
    page_cl = find_value(html, 'PAGE_CL', 3, ',')
    page_label = find_value(html, 'PAGE_BUILD_LABEL', 4)
    variants_checksum = find_value(html, 'VARIANTS_CHECKSUM', 4)

    # Get remaining comments (the same as pressing the 'Show more' button)
    while page_token:

        data = {
            'session_token': session_token
        }

        params = {
            'action_get_comments': 1,
            'pbj': 1,
            'ctoken': comment_token,
            'continuation': comment_token,
            'itct': itct
        }

        session.headers.update({
            'Content-Type': 'application/x-www-form-urlencoded',
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0',
            'X-SPF-Previous': url,
            'X-SPF-Referer': url,
            'X-YouTube-Client-Name': client_name,
            'X-YouTube-Client-Version': '2.20180905',
            'X-YouTube-Page-CL': page_cl,
            'X-YouTube-Page-Label': page_label,
            'X-YouTube-Utc-Offset': '420',
            'X-YouTube-Variants-Checksum': variants_checksum,
        })

        if threshold >= 12:
          print('I am sleeping, sorry!')
          time.sleep(20)
          threshold = 0
        if threshold < 12:
          threshold += 1

        response = ajax_request(
            session, YOUTUBE_COMMENTS_AJAX_URL, params, data)
        if not response:
            break

        session_token = response['xsrf_token']

        try:
            itemSections = response['response']['continuationContents']['itemSectionContinuation']
        except:
            print('Comment continuationContents error')
            time.sleep(5)
            continue

        try:
            comments = itemSections['contents']
        except:
            break

        # reply_cids.extend(extract_reply_cids(html))
        for comment in extract_comments(comments):
            yield comment['comment']
            if comment['replies'] != False:
                reply_continuation = comment['replies']['continuation']
                reply_itct = comment['replies']['clickTrackingParams']
                for reply in download_replies(session, session_token, reply_continuation, reply_itct, 2):
                    yield reply

        try:
            continuations = itemSections['continuations'][0]['nextContinuationData']
        except:
            break
        else:
            itct = continuations['clickTrackingParams']
            comment_token = continuations['continuation']

        time.sleep(sleep)

def download_replies(session, session_token, comment_token, itct, sleep=1):
    page_token = True

    # Get remaining comments (the same as pressing the 'Show more' button)
    while page_token:

        data = {
            'session_token': session_token
        }

        params = {
            'action_get_comment_replies': 1,
            'pbj': 1,
            'ctoken': comment_token,
            'continuation': comment_token,
            'itct': itct
        }
        


        response = ajax_request(
            session, YOUTUBE_COMMENTS_AJAX_URL, params, data)
        if not response:
            break

        try:
            commentRepliesContinuation = response[1]['response']['continuationContents']['commentRepliesContinuation']
        except:
            print('Replies continuationContents error')
            time.sleep(5)
            continue

        try:
            contents = commentRepliesContinuation['contents']
        except:
            break
        else:
            for content in contents:
                item = content['commentRenderer']
                contentText = item['contentText']

                try:
                    text = contentText['simpleText']
                except:
                    runs = contentText['runs']
                    text = ''
                    for run in runs:
                        text += run['text']        
                
                yield {
                    'rid': item['commentId'],
                    'text': text,
                    'time': item['publishedTimeText']['runs'][0]['text'],
                    'author': item['authorText']['simpleText'],
                    'authorid': item['authorEndpoint']['browseEndpoint']['browseId'],
                    'likes': item['likeCount']
                }

        try:
            continuations = commentRepliesContinuation['continuations'][0]['nextContinuationData']
        except:
            break
        else:
            itct = continuations['clickTrackingParams']
            comment_token = continuations['continuation']
        
        time.sleep(sleep)


def main(argv):
    parser = argparse.ArgumentParser(add_help=False, description=(
        'Download Youtube comments without using the Youtube API'))
    parser.add_argument('--help', '-h', action='help',
                        default=argparse.SUPPRESS, help='Show this help message and exit')
    parser.add_argument(
        '--youtubeid', '-y', help='ID of Youtube video for which to download the comments')
    parser.add_argument(
        '--output', '-o', help='Output filename (output format is line delimited JSON)')

    try:
        args = parser.parse_args(argv)

        youtube_id = args.youtubeid
        output = args.output

        if not youtube_id or not output:
            parser.print_usage()
            raise ValueError(
                'you need to specify a Youtube ID and an output filename')

        print('Downloading Youtube comments for video:', youtube_id)
        count = 0
        with open(output, 'w') as fp:
            for comment in download_comments(youtube_id):
                print(comment)
                print(json.dumps(comment), file=fp)
                count += 1
                sys.stdout.write('Downloaded %d comment(s)\r' % count)
                sys.stdout.flush()
        print('\nDone!')

    except Exception as e:
        print('Error:', str(e))
        sys.exit(1)


if __name__ == "__main__":
    main(sys.argv[1:])
`

**Comment by egbertbouman** [comment]
Great, thanks for sharing your code! Apparently, I forgot to about the "Show more replies" link while downloading replies. That should be fixed now.

Unfortunately, I think this is the best we can do using the newer API, since going through the website will also only get you 291 comments. This is why I also kept the old API for non-live videos.

**Comment by d0tN3t** [comment]
Damn! I played around with the new update. It's really good. I was having some issues with my version when using it under multiprocessing.  But your update was a lot more elegant and I think faster.

Basically the way I have it scaled out is I have 5 separate machines using their own VPNs to scrape the comments and each machine is using 8 processes. So that's 40 continuous processes in total, going on at any given time, each process grabbing a video. I originally had it at 80 processes but YouTube started blocking the IPs. So I backed off.  I'm using Redis as the Queue from which they grab a list of video_ids and MongoDB for the main DB. So I adapted your update and its really good! A lot smoother! Thank you so much. I really appreciate it!

**Comment by egbertbouman** [comment]
Cool! It sounds like you're a professional Youtube comment scraper :sunglasses:

Good to hear you approve of the new version of the script. It should be a bit faster now, but that's mostly because I changed the timings a bit. I guess if we really wanted to speedup the comment downloading we could use something like asyncio and do multiple requests at the same time :smiling_imp:.
