### ISSUE TITLE
Extracting all the comments and replies as well

### ISSUE THREAD

**Issue by s-fatemeh-ebrahimi** [egbertbouman/youtube-comment-downloader#134]
Hello,
I wanted to ask you how I can extract all the comments and replies since your script only scrapes the comments, and I haven't found a solution to scrape the replies as well. Thanks in advance.

**Comment by egbertbouman** [comment]
It should be extracting replies as well. Replies will have a `.` in their comment ID, like this:
`<ID of original comment>.<ID of reply>`.

**Comment by s-fatemeh-ebrahimi** [comment]
Thank you for your response. I'm still unable to extract replies using the script, despite following your instructions. Also, the script retrieved more entries (2566) than expected (1326). Could you clarify these issues?

**Comment by heyeanne34** [comment]
how to scarpe replies
