### ISSUE TITLE
Returns zero comments

### ISSUE THREAD

**Issue by gitdude1** [egbertbouman/youtube-comment-downloader#139]
I've been using v0.1.61 for the last couple of years without issues until Friday when the program started returning '0 comments downloaded' for all videos. I downloaded and installed v0.1.70 with the same results (the app now reports 1 comment for all videos due to a minor initialisation bug introduced in '__init__.py').

I installed and ran another extraction app 'yt-dlp' and got the same results. A bug report post there stated that Google was A/B testing/trialling some changes to their software so that some users around the world would be adversely impacted while others would not.

**Comment by debora-alayo** [comment]
i have Downloaded 1 comment(s) and the file is empty

**Comment by deekshaVarshney** [comment]
yes same with me. for 90% urls it is not downloading.

**Comment by 1369sbo** [comment]
Can confirm it was working normally last time I used it before today ( a week or so back), but now I get '...Downloaded 1 comment(s)
...' on a video with over a thousand comments (yet output file is empty)

**Comment by egbertbouman** [comment]
Thanks for letting me know! I'll take a look.

**Comment by egbertbouman** [comment]
It should be working again. Youtube made some changes, so some values may be different now. For instance, I noticed for the author we now have the username instead of the name linked to the account.
