### ISSUE TITLE
Reply destination is not displayed

### ISSUE THREAD

**Issue by soojin557** [egbertbouman/youtube-comment-downloader#141]
Reply destination is not displayed.

Looking at the code

```
   result = {'cid': properties['commentId'],
                 'text': properties['content']['content'],
                 'time': properties['publishedTime'],
                 'author': author['displayName'],
                 'channel': author['channelId'],
                 'votes': toolbar['likeCountLiked'],
                 'replies': toolbar['replyCount'],
                 'photo': author['avatarThumbnailUrl'],
                 'heart': toolbar_state.get('heartState', '') == 'TOOLBAR_HEART_STATE_HEARTED',
                 'reply': '.' in properties['commentId']}
```

  'reply': '.' in properties['commentId']   seems to display the reply destination, but I couldn't get it properly even when I ran the script.

Is it because the YouTube specifications have changed that I can't get it anymore?

**Comment by egbertbouman** [comment]
The reply field is a boolean indicating whether or not the current comment is a reply to another comment.

When replied is `true`, the `cid` should be formatted as follows: \<ID of parent>.\<ID of reply>
