### ISSUE TITLE
[BUG] incorrect votes.

### ISSUE THREAD

**Issue by minamotorin** [egbertbouman/youtube-comment-downloader#143]
https://github.com/egbertbouman/youtube-comment-downloader/blob/420650fbc5f8534dd21be5d6edc57aae12ee5bba/youtube_comment_downloader/downloader.py#L131

I think this should

```python3
                          'votes': toolbar['likeCountNotLiked'],
```

~`likeCountLiked` is used **when the user clik “like button”**, and otherwise `likeCountNotLiked` is used.~ See https://github.com/yt-dlp/yt-dlp/pull/9775#issuecomment-2074980879.

Thanks.

**Comment by egbertbouman** [comment]
Nice find, thank you! You're absolutely correct. Apparently, `votes` was always 1 vote too high. This should be fixed now.
