### ISSUE TITLE
Type of votes

### ISSUE THREAD

**Issue by minamotorin** [egbertbouman/youtube-comment-downloader#144]
https://github.com/egbertbouman/youtube-comment-downloader/blob/bb4d69ebb200f7f8d1aeb175cd2f2775371f8590/youtube_comment_downloader/downloader.py#L131

Thanks for quick fix!

Votes is integer if 0, in the other case, it is string.
I think `'votes': toolbar['likeCountNotliked'].strip() or '0',` is better for compatibility with old version.

Thanks.

**Comment by egbertbouman** [comment]
Yeah, you're right. It wasn't paying attention, and should have made it a `str`. I created a new release where `votes` is a string again.

**Comment by minamotorin** [comment]
Thanks for fixing!
