### ISSUE TITLE
add direct way to link a reply to its parent comment in the output so we can distinguish if its a reply or main comment

### ISSUE THREAD

**Issue by heyeanne34** [egbertbouman/youtube-comment-downloader#148]
is thre a command that has an identifier for these?

**Comment by egbertbouman** [comment]
There's a reply boolean in the comment output: `comment['reply']` will be `True`/`False` depending on whether or not it's a reply to another comment. If you want the comment ID of the parent, you can just do something like `comment['cid'].split('.')[0]`.
