### ISSUE TITLE
0 comments downloaded

### ISSUE THREAD

**Issue by githb123** [egbertbouman/youtube-comment-downloader#149]
Hi, The downloading doesn't work for this URL. I have just now installed a fresh version via pip install. pip list says it's version "0.1"

URL: https://www.youtube.com/watch?v=V4HMm8nFLNA

The output file is empty.

Downloading Youtube comments for video: V4HMm8nFLNA
Downloaded 0 comment(s)
[57.75 seconds] Done!

Please note that apparently according to comments in this issue for yt-dlp https://github.com/yt-dlp/yt-dlp/issues/9358 the format of the comments section is inconsistent/alternating so the downloader should probably first verify which format is being used and then run the appropriate function.

**Comment by egbertbouman** [comment]
It's working fine for me with the latest version.
To ensure you're running the latests version run: `pip install youtube-comment-downloader -U`

**Comment by Roxy45l** [comment]
hello my friend. For a while, YouTube does not return the comments if you make too many requests and the requests are 429. I use proxy when sending requests.Could a captcha problem occur occasionally during this process or something different?
