### ISSUE TITLE
BUG: 3.1K Votes are counted as 31 votes

### ISSUE THREAD

**Issue by nicolas-g** [egbertbouman/youtube-comment-downloader#152]
For comments where the number of votes exceed 1K , it will be stored in the json file as 1 .

**Comment by egbertbouman** [comment]
Thanks for the report. I've done some testing, but I haven't been able to reproduce this.

The script tries to extract the comments exactly as Youtube shows them to the user, meaning in this case that "votes" would be "3,1K". There is no attempt to convert this string into a number.

**Comment by nicolas-g** [comment]
@egbertbouman thanks for the quick response and my apologies, it seems the issue was with the jq query I was using and not with the youtube-comment-downloader.
