### ISSUE TITLE
lately the script seems to hang on downloading comments intermittently

### ISSUE THREAD

**Issue by ericj112** [egbertbouman/youtube-comment-downloader#18]
Lately, the script seems to hang on downloading the comments, it's intermittent as i can download the comments fully on the same video other times.
I'm currently trying to log the errors to get any feedback, might run with strace if nothing shows up, all i see now is the process in "ps" and comments not fully downloaded.

**Comment by aliasgar1530** [comment]
Same here

**Comment by egbertbouman** [comment]
I haven't noticed any problems in the last few months, so I'm closing this issue.

**Comment by spiralofhope** [comment]
I recently tested with https://www.youtube.com/watch?v=koPmuEyP3a0, which has ~450k comments, and it seems to have worked.

It did not conclude by reporting the number of comments downloaded though.
