### ISSUE TITLE
where to specify a Youtube ID and an output filename

### ISSUE THREAD

**Issue by Iphytech** [egbertbouman/youtube-comment-downloader#2]

**Comment by hairypaulsack** [comment]
Did you not read the README.md or was the description lacking the help a month ago?? Normally you can always call the help.. 

windows = '/?'
ex: 'dir /?'

linux = --help or -h
ex: ls --help or ls -h

cross platform languages such as python follow the linux scheme. meaning typically with python scripts, on windows help is called via:
ex: --help or -h


anyway, just as the help states:

downloader.py --youtubeid AwOEPI0KkCs -output 'downloader_output.txt
or
downloader.py -y AwOEPI0KkCs -o 'downloader_output.txt

pay attention to '-' vs '--'
abbreviations or shorthand flags (whatever it is called) is always one '-' and words are always two '--'
abbrev is the most commonly used flags; hence the faster '-x' as opposed to '--'wordx'

**Comment by budi4747** [comment]
Just a note. 
I'm on Windows 10 x64 2016 LTSB 1607 running Python 2.7.14.

Some youtube's video ID have "-" on it. 

Example:

http://www.youtube.com/watch?v=-70ICvYQTQo

Using either:

`python downloader.py --youtubeid -70ICvYQTQo -output outjsonFile.json`

or

`python downloader.py -y -70ICvYQTQo -o outjsonFile.json`

will produce "ERROR"

and I have to enclose the parameter in Quotes:

`python downloader.py "--youtubeid=-70ICvYQTQo" "--output=outjsonFile.json"`

**Comment by ediowar** [comment]
Ubuntu 16.04 64-bit, Python 2.7.12
`downloader.py -y -LjuN26Sx54 -o outjsonFile.json` produce error: argument --youtubeid/-y: expected one argument

**Comment by ealgase** [comment]
> Ubuntu 16.04 64-bit, Python 2.7.12
> `downloader.py -y -LjuN26Sx54 -o outjsonFile.json` produce error: argument --youtubeid/-y: expected one argument

Literally read the comment above you.

**Comment by ediowar** [comment]
Thanks, works.

**Comment by egbertbouman** [comment]
I added a note about this in README.md.
