### ISSUE TITLE
I run this script but i didnt got any comments

### ISSUE THREAD

**Issue by aliasgar1530** [egbertbouman/youtube-comment-downloader#22]
It runs a few mins didn't give any error but json file is empty 
`Done!`

**Comment by d0tN3t** [comment]
Can you share the video that you're having problems with?

**Comment by aliasgar1530** [comment]
https://youtu.be/VL88vzDXA94

**Comment by d0tN3t** [comment]
I was able to capture it

![image](https://user-images.githubusercontent.com/11362484/57496687-f0fa2980-7299-11e9-947e-de28432e884c.png)

**Comment by d0tN3t** [comment]
Ok,

So I have a modified version of this script, but I don't think that's the issue. 
So try this:
cd into the directory that has the script, then run this command in your terminal.
`python downloader.py -y dvOnYLDg8_Y -o sigrid_test.json`

**Comment by aliasgar1530** [comment]
Ok so now it works 
thanks 
Btw any idea how I just extract comments from json file without any other info like authors

**Comment by d0tN3t** [comment]
Remove what you don't want from the "yield" section. And then remove "order
by time" from params, so that you don't get an error, unless you want to
keep the time.

**Comment by aliasgar1530** [comment]
Ok
