### ISSUE TITLE
Recently i'm getting Error: write() argument 1 must be unicode, not str

### ISSUE THREAD

**Issue by ericj112** [egbertbouman/youtube-comment-downloader#23]
The script was working great, a few weeks ago i started getting the error
Error: write() argument 1 must be unicode, not str

I'm doing ./downloader.py --youtubeid uE89Tzd3Ajk --output /tmp/comments

Downloading Youtube comments for video: uE89Tzd3Ajk
Error: write() argument 1 must be unicode, not str

tested on ubuntu 16.04 python 2.7.12

Any ideas?
Thanks

I just tried with python3.5 it still works.

**Comment by egbertbouman** [comment]
@ericj112 You're right, apparently, there was an issue with Python 2. It should be fixed now. Could you try again with the latest master?

**Comment by ericj112** [comment]
Works like a charm, thanks.
