### ISSUE TITLE
Fails to download when ID starts with - (dash)

### ISSUE THREAD

**Issue by maferv** [egbertbouman/youtube-comment-downloader#25]
For example **-6L6WxN3npI**

Error is:
`comytdl: error: argument --youtubeid/-y: expected one argument`

I appreciate the script, please fix this

**Comment by maferv** [comment]
Thanks @TemporaryUsername12481 
This should be in the docs!

**Comment by egbertbouman** [comment]
Updated the README.md to reflect this.
