### ISSUE TITLE
Small bug with bold char.

### ISSUE THREAD

**Issue by d0tN3t** [egbertbouman/youtube-comment-downloader#29]
In the live video portion, if the code comes across anything bold in the comment it will wrap up the comment as if it hit the end. 

YouTube link:
https://www.youtube.com/watch?v=FBCLNEDq1D0

Example: 
![image](https://user-images.githubusercontent.com/11362484/78412183-14c40d80-75d8-11ea-951d-78bdcbed0054.png)

The script returns:
"Viv, buddy. If you are going to continue with these "Live Chats", then you "

I'll try to look for a fix. My assumption is that because it creates a different HTML-tag, then the script doesn't recognize it. 

![image](https://user-images.githubusercontent.com/11362484/78412320-87cd8400-75d8-11ea-860f-141b99b1db49.png)

**Comment by egbertbouman** [comment]
Thank for letting me know! I just pushed a fix for this issue. Now, you should get all the text, but you will lose the formatting. I stripped away the formatting because I didn't want to deal with adding my own HTML tags to the comments.

**Comment by linxon** [comment]
@egbertbouman hi!
it works with py3 ?

**Comment by d0tN3t** [comment]
@egbertbouman  You beast! That was fast! Thank you, I just ran the code and you fixed it!
