### ISSUE TITLE
Maybe the "votes" field is not right when it is zero in `download_comments_old_api`

### ISSUE THREAD

**Issue by BD777** [egbertbouman/youtube-comment-downloader#30]
When using `download_comments_old_api`, there is no zero votes in comment list. 
There are 2 elements with class `like-count`: they are 
class="like-count on" and class="like-count off”, and "like-count on" = "like-count off" + 1.

Note that, when real votes is zero, element class="like-count off" doesn't exist.

So here is how I make it work:
  I change the code in `extract_comments` to
`vote_sel = CSSSelector('.like-count')` -> `vote_sel = CSSSelector('.like-count.off')`
`'votes': vote_sel(item)[0].text_content()` -> `'votes': vote_sel(item)[0].text_content() if len(vote_sel(item)) > 0 else 0,`

**Comment by egbertbouman** [comment]
@BD777 You're absolutely right. Thanks for letting me know!

Is it OK is I push your fix to the master branch myself, or would you prefer to make a PR for it?

**Comment by BD777** [comment]
> @BD777 You're absolutely right. Thanks for letting me know!
> 
> Is it OK is I push your fix to the master branch myself, or would you prefer to make a PR for it?

yup you could just push my fix to the branch : )

**Comment by egbertbouman** [comment]
Just pushed the fix to master. Thanks again!
