### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ediowar** [egbertbouman/youtube-comment-downloader#31]
When running with `$ python downloader.py`
```
  File "downloader.py", line 98
    yield from search_dict(v, key)
             ^
SyntaxError: invalid syntax
```
When running with `$ python3 downloader.py` no error.
Ubuntu 16.04 64-bit, Git revision https://github.com/egbertbouman/youtube-comment-downloader/commit/9194bf8c21196f244c0fe02a2ddaa4053d38bd18
Need to make a change to [Usage](https://github.com/egbertbouman/youtube-comment-downloader#usage).

**Comment by d0tN3t** [comment]
@ediowar  Hey, just doing a quick search on Stackoverflow. Are you running 2.7?
![image](https://user-images.githubusercontent.com/11362484/79371822-968e3200-7f1a-11ea-9a78-7d2caa0182a6.png)

**Comment by ediowar** [comment]
Yes.

**Comment by egbertbouman** [comment]
Oops, it seems I broke Python 2 compatibility. I just pushed a fix for this.

@ediowar Could you please see if it's working now?

**Comment by ediowar** [comment]
Fixed.

**Comment by ediowar** [comment]
Formats vary slightly:
1."photo" , 2."votes" , ..... is for Python 3.5.2
1."votes" , 2."photo" , ..... is for Python 2.7

**Comment by egbertbouman** [comment]
@ediowar Dictionaries provide no guarantees on ordering of keys, so I don't consider this an bug.
