### ISSUE TITLE
I am unable to download parent comment with this code.

### ISSUE THREAD

**Issue by sanidhyasomani** [egbertbouman/youtube-comment-downloader#33]
Can you help me

**Comment by d0tN3t** [comment]
I'm not entirely sure what the "parent comment" is. 
Is this the first comment, main-thread, reply-thread? 

I would be more than happy to test it out for you and see if I can't recreate the issue, if you can please provide me with the video id that you're trying to download from. 👍

**Comment by sanidhyasomani** [comment]
Hello,
Parent comment is the main thread.
The current code extract all comments both main thread as well as reply
thread. I want to extract only main thread.

let's take this video for test purpose
https://www.youtube.com/watch?v=sMAVhkFEeRw
It has total 15 comments, 14 main comment and 1 replies..
Please help me extract only 14 main comments.

Thank you
Sanidhya

**Comment by egbertbouman** [comment]
It's currently not possible to skip the replies. However, you can just filter out the replies by looking at the `cid` of the comments. If the comment is a reply it will have a `.` in the middle.

**Comment by d0tN3t** [comment]
@sanidhyasomani 
Ahh ok, I understand what you mean. This possible but with a few caveats. I'm not entirely sure why you would want to do it...but who am I to judge lol.

1. The simplest way to do it would be to filter out the comment `cid` that have a period in them `.` (it separates main thread `cid` with reply `cid`) just like @egbertbouman mentioned. 

2. The code below is what you're looking for but it would drastically alter the main downloader found in this git repo (IMHO). So I would advise against mixing the two together because it seems like it would take some major refactoring. 

The code below just spits out the comments into a list. If you're really serious about proceeding with this method, then you'll just want to swap out the write-to JSON file, from the one that is in the `main()` function at the bottom of the `downloader.py` file from the git-repo. 

Best of luck, and thank you for elaborating more on your issue!

`from __future__ import print_function

import os
import sys
import time
import json
import requests
import argparse
import lxml.html

from lxml.cssselect import CSSSelector
from datetime import timedelta`

`YOUTUBE_COMMENTS_URL = 'https://www.youtube.com/watch?v={youtube_id}'
YOUTUBE_COMMENTS_AJAX_URL = 'https://www.youtube.com/comment_service_ajax'

USER_AGENT = 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36'`

`def find_value(html, key, num_chars=2, divider='"'):
    pos_begin = html.find(key) + len(key) + num_chars
    pos_end = html.find(divider, pos_begin)
    return html[pos_begin: pos_end]`

`def extract_comments(comments):
    for comment in comments:
        item = comment['commentThreadRenderer']['comment']['commentRenderer']
        contentText = item['contentText']

        try:
            text = contentText['simpleText']
        except:
            runs = contentText['runs']
            text = ''
            for run in runs:
                text += run['text']        

        try:
            replies = comment['commentThreadRenderer']['replies']['commentRepliesRenderer']['continuations'][0]['nextContinuationData']
        except:
            replies = False
        
        yield {
            'comment': {
                'cid': item['commentId'],
                'text': text,
                'time': item['publishedTimeText']['runs'][0]['text'],
                'author': item['authorText']['simpleText'],
                'authorid': item['authorEndpoint']['browseEndpoint']['browseId'],
                'likes': item['likeCount']
            },
            'replies': replies
        }`

`def ajax_request(session, url, params, data, retries=10, sleep=20):
    for _ in range(retries):
        response = session.post(url, params=params, data=data)
        if response.status_code == 200:
            response_dict = json.loads(response.text)
            return response_dict
        else:
            time.sleep(sleep)`

`def download_comments(youtube_id, sleep=1):
    session = requests.Session()
    session.headers['User-Agent'] = USER_AGENT

    # Get Youtube page with initial comments
    url = YOUTUBE_COMMENTS_URL.format(youtube_id=youtube_id)
    response = session.get(url)
    html = response.text

    page_token = True
    session_token = find_value(html, 'XSRF_TOKEN', 4)
    comment_token = find_value(html, 'COMMENTS_TOKEN', 4)
    itct = find_value(html, 'itct', 3)
    client_name = find_value(html, 'INNERTUBE_CONTEXT_CLIENT_NAME', 2, ',')
    client_version = find_value(html, 'INNERTUBE_CONTEXT_CLIENT_VERSION', 3)
    page_cl = find_value(html, 'PAGE_CL', 3, ',')
    page_label = find_value(html, 'PAGE_BUILD_LABEL', 4)
    variants_checksum = find_value(html, 'VARIANTS_CHECKSUM', 4)

    # Get remaining comments (the same as pressing the 'Show more' button)
    while page_token:

        data = {
            'session_token': session_token
        }

        params = {
            'action_get_comments': 1,
            'pbj': 1,
            'ctoken': comment_token,
            'continuation': comment_token,
            'itct': itct
        }

        session.headers.update({
            'Content-Type': 'application/x-www-form-urlencoded',
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0',
            'X-SPF-Previous': url,
            'X-SPF-Referer': url,
            'X-YouTube-Client-Name': client_name,
            'X-YouTube-Client-Version': '2.20180905',
            'X-YouTube-Page-CL': page_cl,
            'X-YouTube-Page-Label': page_label,
            'X-YouTube-Utc-Offset': '420',
            'X-YouTube-Variants-Checksum': variants_checksum,
        })

        response = ajax_request(
            session, YOUTUBE_COMMENTS_AJAX_URL, params, data)
        if not response:
            break

        session_token = response['xsrf_token']

        try:
            itemSections = response['response']['continuationContents']['itemSectionContinuation']
        except:
            print('Comment continuationContents error')
            time.sleep(5)
            continue

        try:
            comments = itemSections['contents']
        except:
            break

        # reply_cids.extend(extract_reply_cids(html))
        for comment in extract_comments(comments):
            yield comment['comment']

        try:
            continuations = itemSections['continuations'][0]['nextContinuationData']
        except:
            break
        else:
            itct = continuations['clickTrackingParams']
            comment_token = continuations['continuation']

        time.sleep(sleep)`

`def worker():
    comment_data  = []
    print('Downloading Youtube comments for video:', 'sMAVhkFEeRw')
    count = 0
    for comment in download_comments('sMAVhkFEeRw'):
        count += 1
        comment_data.append(comment)
        print('Downloaded %d comment(s)\r' % count)
    return comment_data`

`data = worker()`


Here is a snapshot of the results when playing around with the code in a Jupyter Notebook.

<img width="676" alt="Screen Shot 2020-05-26 at 1 22 21 PM" src="https://user-images.githubusercontent.com/11362484/82936382-1f55b000-9f54-11ea-9907-c8d1f998f823.png">

**Comment by sanidhyasomani** [comment]
Thank you for helping me. I am facing some error with the code.
![Screenshot_193](https://user-images.githubusercontent.com/31672451/82975929-6f3b8200-9ffb-11ea-9dd6-c203225d7ce2.jpg)
Please create it as a github repo similar as downloader.py so that with the help of this code i can download the main threads in json file.

**Comment by d0tN3t** [comment]
@sanidhyasomani 

Hey! 

Sorry about that. Try replacing the `USER_AGENT` line with this:

`USER_AGENT = 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36'`

Let me know if that works.

**Comment by sanidhyasomani** [comment]
Thank you.
It is working but can you help me to get output in json or csv file

**Comment by bertainsikt** [comment]
Hi d0tN3t,
I'm also getting an error with in the 'ajax_request(session, YOUTUBE_COMMENTS_AJAX_URL, params, data)'. I've tried changing the User-Agent as you suggested, but it doesn't fix the problem . Do you have any other suggestion? Thank you so much

**Comment by d0tN3t** [comment]
@bertainsikt Sorry I haven't had much time to come in and work on it. I'm not entirely sure what's wrong and it would need to be debugged further.
However, if you're in hurry and need the fix in a pinch, then @egbertbouman is correct on what he posted. (further up the thread) Like he said the only difference between main-thread and reply-thread is that the reply thread has a `.` in the middle of the id. 

`if not "." in cid:'
   ... _do something_

<img width="619" alt="Screen Shot 2020-07-17 at 11 22 43 AM" src="https://user-images.githubusercontent.com/11362484/87808990-3f9d3f00-c820-11ea-90b8-92116bbee7f4.png">

**Comment by laz08** [comment]
Hi, I'm also unable to run the code and crashes when first calling the `ajax_request`  method.

It seems to me that they changed how they handle the user agents yet again, although I'm not sure? A quick search on Google has shown me that they are removing the option to load the old YT layout (for example, by setting the User Agent to `'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'.` Maybe that's related?

A further look on the code tells me that the response never returns me a response in the `ajax_request` method with the field 'text' (only `dict_keys(['_content', '_content_consumed', '_next', 'status_code', 'headers', 'raw', 'url', 'encoding', 'history', 'reason', 'cookies', 'elapsed', 'request', 'connection'])` )

Any idea on how to solve this?

Thanks

**Comment by egbertbouman** [comment]
@laz08 The `text` attribute is probably just a property, so it won't show up in `response.__dict__`. Could you try printing `response.status_code` to see if the server if responding as expected?

**Comment by d0tN3t** [comment]
Hey @laz08 !

Could you provide the video-id that you're experiencing this with? I had run into this issue as well but in reverse (dealing with the new YT-API) a year or two back. I have a test-box that uses the old UI and at the header, there is a banner stating that "Youtube is phasing out this UI and to update". So this may have to do with the old API being phased out. Can you confirm the code works on previous live videos, but not on regular video postings? 

Following these instructions, this workaround doesn't seem to work anymore
![image](https://user-images.githubusercontent.com/11362484/88064971-990fb180-cb31-11ea-96a5-db33f70da558.png)

**Comment by laz08** [comment]
Thanks for the quick replies!

The issue happens with the  code as-is that @d0tN3t  himself shared previously up in this thread and with the change of USER_AGENT to 
 `USER_AGENT = 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36'`

I have tried to  change the USER_AGENT to the googlebot to no avail as mentioned in my last comment, so I have reverted it back to the one suggested above.

The Video ID is the one shared in this issue too: `sMAVhkFEeRw`. Changing it to something more classic like `dQw4w9WgXcQ` does not help, same error happens. 

I changed the `ajax_request` with a couple of prints.

```

def ajax_request(session, url, params, data, retries=10, sleep=20):
    for _ in range(retries):
        response = session.post(url, params=params, data=data)
        print("Status code: ")
        print(response.status_code)
        print("Text: ")
        print(response.text)
		
        if response.status_code == 200:
            response_dict = json.loads(response.text)   # !! Crashes here
            return response_dict
        else:
            time.sleep(sleep)

```

The result as shown in the attached screenshot is that .text is empty:

![image](https://user-images.githubusercontent.com/7511960/88071997-ce89be80-cb74-11ea-9878-a8e02b19900d.png)


I am not sure what you are referring to as _live videos_, do you have an example?

**Comment by egbertbouman** [comment]
@laz08 Oops, I didn't realize that this was about the script @d0tN3t posted earlier.

Looking at the script is seems quite different from what's currently in the repo. After some debugging, the values of `ctoken`/`continuation`/`itci` seem incorrect. Youtube probably changed something which made it stop working.

**Comment by d0tN3t** [comment]
@laz08 
Oh ok, that makes more sense. My apologies. That block of code was just trying to solve a problem that a user was looking for (they wanted only the parent comments w/out replies). The main repo is separate from that. And incidentally, the main repo can handle that user's requests just by removing comments with a `.` (period) in the `cid` field for the json-document.

I'll leave it up to @egbertbouman to decide that if it's causing too much confusion I'll be more than happy to delete the code from this issue.

**Comment by d0tN3t** [comment]
@laz08 

 Sidenote:
You asked about a reference to what I meant by a "live" video meant. Below is a good example. I don't know what the official name for these types of videos are called, but they're posted after going live. 
`https://www.youtube.com/watch?v=hAsZCTL__lo` 

These types of videos can only be downloaded via YouTubes API. Hence why you see these two functions...

**Line 47**
`def download_comments_new_api(youtube_id, sleep=1):`

**Line 110**
`def download_comments_old_api(youtube_id, sleep=1):`

**Comment by laz08** [comment]
I see, @d0tN3t , I wasn't aware of that distinction, good to know and thanks for the prompt example. 

So i've switched back to the original code found in the repo and it's now working. Not sure why it didn't work previously. I must have messed up. In any case, sorry for the confusion.
I'll stick to the `.` distinction to determine whether I am dealing with a parent comment or otherwise.

Thanks, both of you, for the quick replies and help.

**Comment by egbertbouman** [comment]
I'm closing this issue since the problems seem to be resolved.

@d0tN3t Thanks for all your help with answering the issues! No need to remove your code, maybe someone still finds it useful.
