### ISSUE TITLE
Comments on archived livestreams are not being downloaded

### ISSUE THREAD

**Issue by cinister** [egbertbouman/youtube-comment-downloader#34]
This issue only affects archived livestreams, comments on normal videos will be downloaded without a hitch.

Steps to reproduce:
1. Find an archived livestream
2. Download comments using YouTube comment downloader
3. YouTube comment downloader finishes without downloading any comments

**Comment by egbertbouman** [comment]
Could you give me an example video?

**Comment by cinister** [comment]
Sure, here are several examples:
https://www.youtube.com/watch?v=3lQUuXKW4FQ
https://www.youtube.com/watch?v=XR0hk700H_4
https://www.youtube.com/watch?v=RMnC4J6-r5k
https://www.youtube.com/watch?v=MMJw0wE2y7c

**Comment by egbertbouman** [comment]
Thanks! This should be fixed now. If the issue reoccurs, feel free to reopen.

**Comment by ediowar** [comment]
https://youtu.be/qFrbmseX9TI
In two of the four download attempts, an unknown error occurs.
`Error: Error returned from server: Неизвестная ошибка.`
