### ISSUE TITLE
Comments on archived livestreams are not being downloaded

### ISSUE THREAD

**Issue by ediowar** [egbertbouman/youtube-comment-downloader#35]
https://youtu.be/qFrbmseX9TI
In two of the four download attempts, an unknown error occurs.
`Error: Error returned from server: Неизвестная ошибка.`

**Comment by egbertbouman** [comment]
I just downloaded the comments 10x in a row, without any issues. My guess is that the server was experiencing problems or you're making too many requests.

**Comment by egbertbouman** [comment]
Before, I was running the script using Python 3.8. After trying to get the comments with Python 2.7, I did get a failure. This should be fixed now. Please let me know if it reoccurs.

**Comment by ediowar** [comment]
I am running the script using Python 3.5.2. There is no issue right now.
