### ISSUE TITLE
Can I download comments from multiple channels and all videos in those channels?

### ISSUE THREAD

**Issue by holygamer** [egbertbouman/youtube-comment-downloader#37]
I use YouTube-DL to run a single batch file which downloads all the videos from multiple channels specified in the batch file. Videos are downloaded into automatically named directories like this:

C:\YouTubeDL\Channel_Name\Video_Title\DateUploaded. Video_Title VideoID.mp4

Does your program allow me to run a single script to download all comments on all videos from several different channels?
If so, how do I do that?

Can I have each of the comments file download into a different directory like the above example? So the comment file will go into the directory created by YouTubeDL.

Thanks

**Comment by egbertbouman** [comment]
Unfortunately, downloading comments per channel is not supported. Currently, only you can only download comments if you have the video ID. However, you could write some additional code to extract the video IDs from a channel, and then use `download_comments` to download the comments.
