### ISSUE TITLE
"Error: generator raised StopIteration" with videos that have info panel

### ISSUE THREAD

**Issue by barbaragribeiro** [egbertbouman/youtube-comment-downloader#38]
I tried to run the script for a live stream (id = TcevjiHMz8I) which has the [COVID-19 info panel](https://support.google.com/youtube/answer/9004474?hl=en&ref_topic=9257092) and it happens that the code searches for `itemSectionRenderer` to find the continuations, but for this type of video there are two `itemSectionRenderer` and the one with the continuations is the second one.
This leads to "Error: generator raised StopIteration"  when the script calls `next()` to the generator created when searching for `nextContinuationData` inside the renderer, since there is none.

**Comment by egbertbouman** [comment]
Thanks for debugging this! I've just pushed a fix that checks if the `itemSectionRenderer` has a `nextContinuationData`.
