### ISSUE TITLE
A little confused.

### ISSUE THREAD

**Issue by d0tN3t** [egbertbouman/youtube-comment-downloader#4]
The code works amazingly! But I don't understand how it's finding these selectors. When I inspect a video, I don't see the selectors. Especially '.user-name'. The other ones don't have exact matches and include 'renderer' in the name. Would you please explain how it works? Thank you!

`def extract_comments(html):
    tree = lxml.html.fromstring(html)
    item_sel = CSSSelector('.comment-item')
    text_sel = CSSSelector('.comment-text-content')
    time_sel = CSSSelector('.time')
    author_sel = CSSSelector('.user-name')`

**Comment by sleiter88** [comment]
Can you tell me how you resolve this?

**Comment by d0tN3t** [comment]
Sorry, it's been a while since I figured it out and it may no longer be the same but what you want to do is revert to the old style of the YouTube layout. This script is fairly old and was scraping off of the old site. You want the version of you YouTube where you don't use "infinite-scroll" to load more, but rather using the button to load more comments. 

Here are the instructions to revert back to the old layout.:

Chrome

    Open a Youtube page

    Press Control+Shift+I (that is an I as in information)

    Application tab on top (may have to click the arrows to view more tabs)

    On the left, in Storage, expand "cookies"

    Click on the cookie for Youtube

    On the right, you should see columns for "Name" and "Value"

    In the Name column, there should be one called "PREF". If this is missing, do something on the 

    Youtube page to create it. Just disable autoplay on a video or change the sort order if you are viewing 
    someone's videos in their profile

    For PREF, double-click the Value to edit it and replace it with f6=8 or add it to what is already there 
    with &f6=8

    Click off of the Value or press enter to save it and then refresh the page. All Youtube pages will now 
    use the old layout

![image](https://user-images.githubusercontent.com/11362484/61554181-eee2e280-aa21-11e9-9032-e6f228373020.png)

**Comment by sleiter88** [comment]
> Sorry, it's been a while since I figured it out and it may no longer be the same but what you want to do is revert to the old style of the YouTube layout. This script is fairly old and was scraping off of the old site. You want the version of you YouTube where you don't use "infinite-scroll" to load more, but rather using the button to load more comments.
> 
> Here are the instructions to revert back to the old layout.:
> 
> Chrome
> 
> ```
> Open a Youtube page
> 
> Press Control+Shift+I (that is an I as in information)
> 
> Application tab on top (may have to click the arrows to view more tabs)
> 
> On the left, in Storage, expand "cookies"
> 
> Click on the cookie for Youtube
> 
> On the right, you should see columns for "Name" and "Value"
> 
> In the Name column, there should be one called "PREF". If this is missing, do something on the 
> 
> Youtube page to create it. Just disable autoplay on a video or change the sort order if you are viewing 
> someone's videos in their profile
> 
> For PREF, double-click the Value to edit it and replace it with f6=8 or add it to what is already there 
> with &f6=8
> 
> Click off of the Value or press enter to save it and then refresh the page. All Youtube pages will now 
> use the old layout
> ```
> 
> ![image](https://user-images.githubusercontent.com/11362484/61554181-eee2e280-aa21-11e9-9032-e6f228373020.png)

Nice! thanks!!
