### ISSUE TITLE
Exclude CID from output

### ISSUE THREAD

**Issue by vanitysys28** [egbertbouman/youtube-comment-downloader#41]
I'm using this script to extract commentors name and profile pictures URL.
Any way to remove the CID from the output? 
After my testing, it seems hard to achieve because it's required in functions.

**Comment by d0tN3t** [comment]
Hey @vanitysys28 

Is this possibly what you're looking to do?
`{"author":comment["author"], "photo":comment["photo"]}`

And then if you decide you want to add the items back in you could just modify the code by repeating the process and adding the `key:value` you'd like to bring back in.

<img width="1116" alt="Screen Shot 2020-07-17 at 11 11 28 AM" src="https://user-images.githubusercontent.com/11362484/87807895-707c7480-c81e-11ea-8718-7ae0594c6864.png">

You would just need to make that change at line **234**

<img width="896" alt="Screen Shot 2020-07-17 at 11 17 31 AM" src="https://user-images.githubusercontent.com/11362484/87808372-36f83900-c81f-11ea-9bb9-5115eb456031.png">

`{"author":comment["author"], "photo":comment["photo"]}`

**Comment by vanitysys28** [comment]
Perfect, that's exactly what I needed!
Just edited comment_json with the right json.dumps so that it gets added to the output file.

Thanks a lot
