### ISSUE TITLE
Missing Authorid

### ISSUE THREAD

**Issue by d0tN3t** [egbertbouman/youtube-comment-downloader#42]
Hey!

I'm not sure when the `authorid` fell off but it must have happened during a PR. 

(New API)
`'authorid': comment['authorEndpoint']['browseEndpoint']['browseId'],`

(Old API)
`'authorid': author_sel(item)[0].attrib['href'].replace('/channel/','').strip(),`

**Comment by egbertbouman** [comment]
I don't remember the `authorid` ever being there. However, yesterday I did add `channel` (see https://github.com/egbertbouman/youtube-comment-downloader/issues/39).

After looking at the code you posted, it looks I forgot to strip the `/channel/` prefix. I just fixed that. Thanks!
