### ISSUE TITLE
Ability to sort comments by rating

### ISSUE THREAD

**Issue by pupkinvaska** [egbertbouman/youtube-comment-downloader#47]
By default the script extracts newest comments first. It lacks the option to sort comments by rating - Top comments first.
As it is not always possible to get rating by the number of likes.

**Comment by d0tN3t** [comment]
@pupkinvaska You could try inserting something like this `sorted(lis, key = lambda i: i['votes'],reverse=True)` before or after line 240's block
`for comment in download_comments(youtube_id):`

**Comment by pupkinvaska** [comment]
@d0tN3t thanks, but sorting by number of likes is not youtube's sorting. Dislikes and the number of replies are also taken into account there.

**Comment by egbertbouman** [comment]
Sorting was added in https://github.com/egbertbouman/youtube-comment-downloader/commit/8710aa4230683329762768b7659eeec6117098ae (see also https://github.com/egbertbouman/youtube-comment-downloader/issues/72).
