### ISSUE TITLE
Comment downloads not working anymore NO JSON object

### ISSUE THREAD

**Issue by ericj112** [egbertbouman/youtube-comment-downloader#50]
Hi, the comments downloading is not working anymore, it says
Downloading Youtube comments for video: t2jam1x5ki4
Error: No JSON object could be decoded
Thanks

**Comment by spiralofhope** [comment]
I love this program, but it also doesn't work for me at the moment.  For now I'm using [youtube-comment-downloader](https://github.com/egbertbouman/youtube-comment-downloader).

**Comment by egbertbouman** [comment]
The script seems to be working fine for me. Perhaps Youtube is requesting a captcha check?

To find out, maybe you could add a print statement just before the HTML response is JSON decoded. You can do this by adding `print(response.text)` just before: https://github.com/egbertbouman/youtube-comment-downloader/blob/c47cf9988d1ed771e635e25cce3036a5df900510/downloader.py#L33

**Comment by spiralofhope** [comment]
I tested and was able to download the comments.  @ericj112 Let me know if you need me to provide it.

**Comment by ericj112** [comment]
It turned out to be it was using ipv6 and youtube was giving me an error 429 too many requests when i tried to wget the page, turning ipv6 off fixed this part of the problem. Thanks for the help all.
