### ISSUE TITLE
Integrate this with youtube-dl?

### ISSUE THREAD

**Issue by LoveHumanity** [egbertbouman/youtube-comment-downloader#55]
Hello, I very much like your program, but would love if it was integrated into youtube-dl as youtube-dl is currently lacking in any feature to download comments.

My specific use case is I download Youtube channels using Youtube-dl but would also like to also have the comments downloaded. Is there anyway for me to do this is some kind of automated way using youtube-dl and your script?

Thanks and hope to hear back from you!

**Comment by egbertbouman** [comment]
I'm not familiar enough with youtube-dl to estimate how difficult it would be to integrate youtube-comment-downloader. However, since both youtube-dl and youtube-comment-downloader can be called from within Python, it would be easy to create a small Python script that suits your needs.

**Comment by LoveHumanity** [comment]
Ok well thank you for your assistance, I will try what you suggested and also ask youtube-dl if they would be at all interested in integrating your script into there project.

**Comment by terrypa** [comment]
> 
> 
> Ok well thank you for your assistance, I will try what you suggested and also ask youtube-dl if they would be at all interested in integrating your script into there project.

did u have any luck with this script? can u share ur progress?
