### ISSUE TITLE
Can't download youtube videos with symbols in their id

### ISSUE THREAD

**Issue by isabelchew** [egbertbouman/youtube-comment-downloader#57]
If the youtube id has symbols in it like "=" or "&" it doesn't seem to work. Is there a way around this? 

Thanks!

**Comment by isabelchew** [comment]
Hm, I removed the characters after the second "=" and it works. Perhaps that's the best way around that.

**Comment by spiralofhope** [comment]
A YouTube ID does not have either of those characters in it.

For example, if is the video:

https://www.youtube.com/watch?v=jNQXAC9IVRw

Then the ID is not `?v=jNQXAC9IVRw`.  It is instead `jNQXAC9IVRw`.

I think you figured it out on your own though.  :)
