### ISSUE TITLE
if the videoid starts with "-" it doesn't work

### ISSUE THREAD

**Issue by ericj112** [egbertbouman/youtube-comment-downloader#6]
youtube-comment-downloader-master$ ./downloader.py --youtubeid -SxV944iB48
usage: downloader.py [--help] [--youtubeid YOUTUBEID] [--output OUTPUT]
downloader.py: error: argument --youtubeid/-y: expected one argument

**Comment by egbertbouman** [comment]
@ericj112 Thanks! This seems to be an issues with Python's argparse module. To work around this you can run the script as follows:
```downloader.py --youtubeid=-SxV944iB48 --output test.txt```

**Comment by egbertbouman** [comment]
If this still doesn't work feel free to reopen the issue.
