### ISSUE TITLE
Create requirements.txt to simplify dependencies

### ISSUE THREAD

**Issue by louie-github** [egbertbouman/youtube-comment-downloader#62]
Hello there 😄 

Keeping in mind that there are only three dependencies which are very simple to install as per the README, I'd respectfully like to suggest creating a requirements.txt file just so that people could simply shoot off a `pip install -r requirements.txt`.

I think the contents could be as simple as:
```
cssselect
lxml
requests
```

I'd also like to suggest changing the README to either say to simply do `pip install -r requirements.txt` if we do create that file, or to say `pip install requests lxml cssselect` if we don't create said file. It's a really simple change, but it beats having to type three commands.

Again, thank you for your work and for your time! Cheers!

**Comment by egbertbouman** [comment]
Thanks for the suggestion 👍
You're right, using a `requirements..txt` is more convenient. I've just added this and updated the README.
