### ISSUE TITLE
Error when downloading from any video

### ISSUE THREAD

**Issue by ylluminarious** [egbertbouman/youtube-comment-downloader#64]
Hi,

Any video I try gives me this rather cryptic error:

```
Error: str() takes at most 1 argument (2 given)
```

I'm using Python 2.7.18. Any idea why this is happening / how to circumvent this error?

**Comment by egbertbouman** [comment]
Looks like there was a compatibility issue with Python 2. This should be fixed now. Thanks for reporting this!

**Comment by ylluminarious** [comment]
@egbertbouman Thanks for fixing this!
