### ISSUE TITLE
Bug: Unable to download comments from YouTube videos other than live streamings

### ISSUE THREAD

**Issue by minamotorin** [egbertbouman/youtube-comment-downloader#66]
Thank you for the last time. Now, I found that I cannot download comments from YouTube videos other than live streamings. No error occured and the log just says there were 0 comment.

I confirmed followings:
  - The issue will occur with both Python 3.9.0 and Python 2.7.18 (Thank you for fixing python 2 issue too)
  - This issue occur with Premieres too
  - It does not matter the video lengt or video quality
  - No problem with YouTube live streamings (It does not matter if the archive has chats or recording or not too)

Environment: 
  - Python 3.9.0 and 2.7.18 with pyenv 1.2.21
  - lxml 4.6.2
  - requests 2.25.0
  - cssselect 1.1.0

Test videos:
  - [other than live streamings](https://www.youtube.com/watch?v=I5RhX06NYvQ)
  - [live streaming](https://www.youtube.com/watch?v=VTiJR7FW2cM)

Log:
```
$ downloader.py -y I5RhX06NYvQ -o notlive
Downloading Youtube comments for video: I5RhX06NYvQ
Downloaded 0 comment(s)
[102.37 seconds] Done!
$ downloader.py -y VTiJR7FW2cM -o live
Downloading Youtube comments for video: VTiJR7FW2cM
Live stream detected! Not all comments may be downloaded.
Downloaded 641 comment(s)
[51.23 seconds] Done!
 ```

**Comment by sinepgnol** [comment]
ditto

**Comment by egbertbouman** [comment]
It looks like Youtube finally stopped supporting the old way of downloading comments (since that URL now returns a 404). This means that we'll have to download comments the same way as we're already doing for live streams. The unfortunate side-effect, however, is that we'll no longer be able to download *all* comments. When I have some time, I'll produce a fix.

**Comment by avalanchesiqi** [comment]
is it possible to collect all the comments under "Newest first" tab via the new api (the one for live streams)? It seems that we only need to locate the correct **continuation** and **itct**..

**Comment by minamotorin** [comment]
Workaround:
```
41c41
<     if r'"isLiveContent":true' in requests.get(YOUTUBE_VIDEO_URL.format(youtube_id=youtube_id)).text:
---
>     if True:
```

https://github.com/egbertbouman/youtube-comment-downloader/blob/cffaecbbc872319d120466a3fb95515b3ba72bb4/downloader.py#L41

**Comment by egbertbouman** [comment]
Everything seems to be working again. The script now no longer makes a distinction between live/not-live videos.

@avalanchesiqi It should be possible to change the sorting, but that's something I'll have to look into.

**Comment by minamotorin** [comment]
Thank you for fixing!
