### ISSUE TITLE
[BUG] Unable to download replies and work forever

### ISSUE THREAD

**Issue by minamotorin** [egbertbouman/youtube-comment-downloader#68]
Hi. It seems that YouTube changed the specification again.

# Description

If there are replies in video's comments, this script work forever and download infinity comments. The output is loop of comments otehr than replies and no replies are downloaded. Sometimes there are lack of normal comments in the output but I think it is what [“we'll no longer be able to download *all* comments”](https://github.com/egbertbouman/youtube-comment-downloader/issues/66#issuecomment-770111746) means.

No problem if there are only normal comments.

I had had this problem sometimes after the latest update (#66) but it work fine after retrying until today. However, this problem will always occur with all videos has replies today.

# Environment

- Python 3.9.0 and 2.7.18 with pyenv 1.2.21
- lxml 4.6.2
- requests 2.25.0
- cssselect 1.1.0

# Test videos

- [has replies](https://www.youtube.com/watch?v=TT4TlZJWnDM)
- [has no reply](http://youtube.com/watch?v=q1oVp2uAyVY)

**Comment by egbertbouman** [comment]
You're right, Youtube changed things again. Thanks for letting me know! I just pushed a fix for this.

> Sometimes there are lack of normal comments in the output but I think it is what [“we'll no longer be able to download _all_ comments”](https://github.com/egbertbouman/youtube-comment-downloader/issues/66#issuecomment-770111746) means.

It means that we may not get the complete number of comments as listed on the Youtube website. However, if a comment can be viewed in the browser the script should download it.

**Comment by minamotorin** [comment]
Thanks for your great work!
