### ISSUE TITLE
Is it possible to get all comments IF you sort by new?

### ISSUE THREAD

**Issue by guerra321** [egbertbouman/youtube-comment-downloader#72]
I noticed that in this video:
https://www.youtube.com/watch?v=s1PvupI5sD0

In the "top comments" section not all comments appear, but if you sort by newest all the comments show up? Maybe someone could look into this? I just found this script.

**Comment by egbertbouman** [comment]
Oh wow, you're right! The last time I checked this it didn't produce extra comments, but it does now.

I've just added an option to set the sorting option. By adding `--sort 0`, you will download the popular comments, and by adding `--sort 1`, you will download the recent comments. The default is 1, as it seems to download the most comments.
