### ISSUE TITLE
Invalid JSON file

### ISSUE THREAD

**Issue by alx-xlx** [egbertbouman/youtube-comment-downloader#74]
```
youtube-comment-downloader --youtubeid W*********U --output tmp/comments_W*********U.json 
```

in the output `.json` file objects need to be separated by commas

![5rYtIpZM40](https://user-images.githubusercontent.com/42188371/115233639-c9729380-a135-11eb-9153-fa721d1a05ba.png)

**Comment by egbertbouman** [comment]
The output is in line delimited JSON. This means that any line within the output file can be parsed as JSON, but not the file as a whole.

I've used delimited JSON because it's easier to append data and process data, especially with large data sets.
