### ISSUE TITLE
browseId error

### ISSUE THREAD

**Issue by FloPinguin** [egbertbouman/youtube-comment-downloader#75]
Thank you for the amazing script. Perfect for running after youtube-dl downloads.

I found an reproducable error with this params:
--youtubeid=r6vNYD6hSk0 --output=test.txt

Response after downloading about 600 comments:
Error: 'browseId'

**Comment by egbertbouman** [comment]
Apparently, one of the comments doesn't have a user attached to it, causing this error. I've just pushed a fix for this.
