### ISSUE TITLE
Error: local variable 'ncd' referenced before assignment

### ISSUE THREAD

**Issue by solomsk** [egbertbouman/youtube-comment-downloader#76]
if the videoid contains "-" ，the python code will except with error:
Error: local variable 'ncd' referenced before assignment

such as:
python downloader.py -y -795DXCu9sk -o ff-795DXCu9sk.json
usage: downloader.py [--help] [--youtubeid YOUTUBEID] [--output OUTPUT]
                     [--limit LIMIT] [--sort SORT]
downloader.py: error: argument --youtubeid/-y: expected one argument

C:\youtube评论>python downloader.py --youtubeid https://www.youtube.com/watch?v=-795DXCu9sk -o "795DXCu9sk.json"
Downloading Youtube comments for video: https://www.youtube.com/watch?v=-795DXCu9sk
Error: local variable 'ncd' referenced before assignment

**Comment by egbertbouman** [comment]
When dealing with IDs that start with a dash, you need to run the script as follows:
`python downloader.py -y=-795DXCu9sk -o 795DXCu9sk.json`
There is a comment about this in the README.md.

**Comment by egbertbouman** [comment]
Duplicate of https://github.com/egbertbouman/youtube-comment-downloader/issues/25.
