### ISSUE TITLE
Error: request() got an unexpected keyword argument 'json'

### ISSUE THREAD

**Issue by bernobi** [egbertbouman/youtube-comment-downloader#79]
Hello and thank you for all, with this occasion!
  I am not sure this is the way, to report problems(or communicate things) related to this wonderful program) . Just registered here.

  Last version that I used successfully was the one from 01 apr 2021.
  When I tried the version from 15 jul 2021, I see : 
Downloading Youtube comments for video: blablabla
Error: request() got an unexpected keyword argument 'json'
.  
  And an empty file is created.
    I used the same command as before: ./downloader.py --youtubeid blablabla --output comments.json
.
    As a side note, on earlier versions, I noticed that when I used the sorting to popular (0) it did not download all the comments, but leaving to the default sort 1 it got them all.

   Kind Regards!

**Comment by egbertbouman** [comment]
This is indeed the right way to report problems, thanks 👍 

Could it be that you're using a really old version of `requests`? If you have pip installed, you can check by running `pip show requests`.
