### ISSUE TITLE
Format issue

### ISSUE THREAD

**Issue by meagain69** [egbertbouman/youtube-comment-downloader#8]
Thank you very much for your script. it runs nice. 

I have a small issue. once it is done scraping, the format is a non json recognized format. 
is there a way to parse out the information in a human readable format? 

tx

sample of scrape:
`{"text": "Very nice build! I actually saw this idea for the hardware on DIY Creators Murphy bed also.\ufeff", "time": "5 hours ago", "author": "BULLY TUBE", "cid": "UgwRXSS46gAhx3-FE1F4AaABAg"}
{"text": "Great project brother, and you have a cute helper there who likes to look cool \ud83d\ude0e when he works.\ufeff", "time": "8 hours ago", "author": "Jason B", "cid": "Ugwc7a3DfADEjn1VJ5Z4AaABAg"}
{"text": "I would have made a shallow cabinet to put stuff inside instead of floating shelves. I'm a lazy guy. I'd hate to have to take stuff off the shelves to use the bed. Great video.\ufeff", "time": "16 hours ago", "author": "altpath", "cid": "UgypCqXA0-b2fbhVcKR4AaABAg"}
{"text": "awesome job!\ufeff", "time": "17 hours ago", "author": "Roomies Garage", "cid": "Ugxycx47mO7_GARHmQJ4AaABAg"}
{"text": "any issues with overspray?\ufeff", "time": "19 hours ago", "author": "ERAUWeatherMan09", "cid": "UgzBs-Bvj4XS7xFbqdV4AaABAg"}
{"text": "Great build! Why is the son already so much cooler than the dad?!? Lol Background chillin!\ufeff", "time": "1 day ago", "author": "symon forte", "cid": "Ugz7YcbkcD_QWlo2WGF4AaABAg"}
{"text": "what about pillows? \ngreat project\ufeff", "time": "1 day ago (edited)", "author": "Badar Almshali", "cid": "UgzxIVpHiZl2bBpbqSN4AaABAg"}
{"text": "\ud83d\udc4dgood job \u0639\u0645\u0644 \u062c\u0645\u064a\u0644\ufeff", "time": "2 days ago", "author": "MOSS KAM", "cid": "Ugx7APiyDCD5qZI3Y7l4AaABAg"}
{"text": "\u0627\u0646\u0627 \u0627\u062d\u062a\u0631\u0645\u0643 \u0644\u0627\u0646\u0643 \u0631\u062c\u0644 \u060c \u0643\u0644 \u0627\u0644\u064a \u0627\u0634\u0648\u0641 \u0634\u063a\u0644\u0647\u0645 \u0644\u0627\u0632\u0645 \u064a\u0627 \u0642\u0637\u0648\u0647 \u0627\u0648 \u062c\u0644\u0628 \u0627\u0648 \u062d\u0645\u0627\u0631 \u064a\u062d\u0648\u0645 \u062d\u0648\u0627\u0644\u064a\u0646\u0647 \u060c \u0628\u0633 \u0627\u0646\u062a \u0648\u0644\u062f\u0643 \u0639\u0646\u062f\u0643\ufeff", "time": "2 days ago", "author": "MOSS KAM", "cid": "UgxB0ChuFgRhu2790nV4AaABAg"}
{"text": "Interesting idea.  not sure about the worthless shelves. I'd probably just go with the one for the support.\ufeff", "time": "2 days ago", "author": "Tim Moen", "cid": "Ugy97inHBSSf2bWjJIN4AaABAg"}
{"text": "You can sleep on your design on your own.\ufeff", "time": "2 days ago", "author": "Tyler G", "cid": "Ugy97inHBSSf2bWjJIN4AaABAg.8c98H6y-sQE8cA4Qj4hDAx"}
{"text": "Cool build.\n\nDoes it squeak at all?\ufeff", "time": "3 days ago", "author": "Patrik", "cid": "Ugz371TXLSOwVWj1wEx4AaABAg"}
{"text": "Looks great and seems to work great as well!\ufeff", "time": "3 days ago", "author": "Maikel Versantvoort", "cid": "Ugx17ten3SjnqpIKYhN4AaABAg"}
{"text": "Nice one Tyler!!\ufeff", "time": "3 days ago", "author": "JT Woodworks", "cid": "Ugy0QjxHNY16cnxeWJN4AaABAg"}
{"text": "Fantastic project, Tyler!  You explained everything very well, and the wood finish looks quite elegant.  Plus, I love that glue squeeze-out straw trick!\ufeff", "time": "3 days ago", "author": "ode2george", "cid": "Ugw136Io5vimdTiQ5LB4AaABAg"}
{"text": "Ahhhh, I can't wait until Hudson can start helping me out in the shop :)   Awesome design!\ufeff", "time": "3 days ago", "author": "Mike and Lauren", "cid": "UgyCzvU0FnCl4TuC3O94AaABAg"}
{"text": "+Mike and Lauren Thanks Mike! Welcome home and congrats on the new little one!\ufeff", "time": "3 days ago", "author": "Tyler G", "cid": "UgyCzvU0FnCl4TuC3O94AaABAg.8c68NiR9cBY8c6ET5ux6zd"}
{"text": "Like that spray job looks like gold... LOL\ufeff", "time": "3 days ago", "author": "Robert Bryson", "cid": "Ugx3xBtgYsctclouHy14AaABAg"}
{"text": "Absolutely a great video! I love how you made it very straight forward and easy to understand. I would also kill for your workshop!  Great job.\ufeff", "time": "3 days ago", "author": "Gene Cavasos DIYGene", "cid": "Ugy6VxZWC_4l-nRtjR54AaABAg"}
{"text": "New subscriber just added...but the problem with that design it's the shelfs. They become obsolete when you are using the bed constantly...atleast they woupd be for me\ufeff", "time": "3 days ago", "author": "epenaloza52", "cid": "Ugwb0jczLlP8RCqHj2V4AaABAg"}
{"text": "+epenaloza52 You need legs and the support. Better to have shelves when and bed is up then nothing.\ufeff", "time": "3 days ago", "author": "Tyler G", "cid": "Ugwb0jczLlP8RCqHj2V4AaABAg.8c5uwS0g6P18c5xModnVpm"}
{"text": "Brilliant idea to have the shelves double as legs/support for the bed! I'll try to remeber that trick for future builds ;)\ufeff", "time": "3 days ago", "author": "Made by Magnus", "cid": "UgyxbZBHwcMkC3kZ_Vd4AaABAg"}
{"text": "Really nice job finish looked great and good to see the little one helping out\ufeff", "time": "3 days ago", "author": "Terence Charlesworth", "cid": "Ugxf0bGgmXZR9OB0Hyx4AaABAg"}
{"text": "I really enjoyed this video, and am thinking about a murphy for my son's apartment (which was my formal livingroom). On a personal note, I am very impressed you are starting your boy off right helping in your shop and his wearing eye protection. Some folks don't really understand how important that is, and I want to compliment you on leading by example.\ufeff", "time": "4 days ago", "author": "Elleanna U", "cid": "UgwCKd48jeXqmXGk9DZ4AaABAg"}
{"text": "This project looks great! Your little guy is awesome help, he's great with the shop vac! Great instructions too.\ufeff", "time": "4 days ago", "author": "Steven Kofoed", "cid": "UgxWyNt_7yUO5_jIxAR4AaABAg"}
{"text": "I really like this Murphy bed. I only question about how high up the bolt is for keeping it closed. I see your wife and am wondering can she reach the latching bolt...lol\ufeff", "time": "4 days ago", "author": "Donnie Gaskill", "cid": "Ugyo7rcLykt-i_-1Red4AaABAg"}
{"text": "definitely using this style of floating shelves in our bathroom remodel...as always, looks great!\ufeff", "time": "4 days ago", "author": "Brad Greenstreet", "cid": "Ugz65vEcwJp9Rj0yp_14AaABAg"}
{"text": "Really nice job...\ufeff", "time": "4 days ago", "author": "Katherine Carroll", "cid": "Ugx0BccUkjtCzmjVIjZ4AaABAg"}
{"text": "COOL! \ud83d\udc4d\ufeff", "time": "4 days ago", "author": "\u0422\u0430\u043b\u044f\u043d \u0424\u0435\u0434\u043e\u0441\u043e\u0432", "cid": "UgyAakWVEFEJVFW0euV4AaABAg"}
{"text": "Murphy beds are just so sweet.  Nice work!\ufeff", "time": "4 days ago", "author": "Hand Tool Rescue", "cid": "UgzS5e58pk4axndUW9Z4AaABAg"}
{"text": "Nice creative use of the lazy Susan as hardware. I'm not sure if access would be possible, but if you used carriage bolts would the low profile heads clear the face frame?\ufeff", "time": "4 days ago", "author": "Jeremy Specce", "cid": "UgzsobN2aLi-Y-aFUiZ4AaABAg"}
{"text": "Great job!  Question, how easy is the sprayer and tubing to clean?\ufeff", "time": "4 days ago", "author": "BronkBuilt", "cid": "Ugz_C1SMVFi_ECNNkgB4AaABAg"}
{"text": "Overall build and that finest stain finish is just amazing.\ufeff", "time": "4 days ago (edited)", "author": "Ravs Ajay", "cid": "UgxjkzpBVKjnURcZKip4AaABAg"}
{"text": "Thanks fo the inexpensive and easy idea!\ufeff", "time": "4 days ago", "author": "Linda Stone", "cid": "UgxLxXK8DbB1nb401PZ4AaABAg"}
{"text": "Another great job Ty.  I again commend you for getting the kids involved.\ufeff", "time": "4 days ago", "author": "Dave Harrington", "cid": "UgzVRgZBQia6BVU3q1J4AaABAg"}
{"text": "Thanks Dave!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "UgzVRgZBQia6BVU3q1J4AaABAg.8c4pAjaJcH18c4sCs2QJqy"}
{"text": "Excellent project, and the mixing of stain and clear coat better; I did the same some time ago with a table top build; had very little stain left and didn\u2019t want to go out and buy more and wanted to finish the build\ufeff", "time": "4 days ago", "author": "Neil Cruz", "cid": "Ugyo_VgsUnkPx1C7XVp4AaABAg"}
{"text": "Thanks for watching Neil!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "Ugyo_VgsUnkPx1C7XVp4AaABAg.8c4nA1e_w2T8c4sC-tk3BH"}
{"text": "It\u2019s unbelievable super. Like\ufeff", "time": "4 days ago", "author": "Mishgan Simple", "cid": "Ugz_7vkeU7C0OClPAsx4AaABAg"}
{"text": "Thanks for watching!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "Ugz_7vkeU7C0OClPAsx4AaABAg.8c4kXn8LFmw8c4sAAQyJHj"}
{"text": "I got a small suggestion I think maybe you could put another bookshelf on the other side my balance it out a little better but that's all your call great job love watching your videos keep up the good work\ufeff", "time": "4 days ago", "author": "Ron EEE", "cid": "UgxcIgC7wpnvrpkkEU14AaABAg"}
{"text": "Well.....I did build one but didn't take into account the light switch! (Left that part out of the video!)\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "UgxcIgC7wpnvrpkkEU14AaABAg.8c4IAAX6MvY8c4s9KHFbEz"}
{"text": "hey tyler i added  a regular door lock to my murphy bed it seems to hold pretty good https://youtu.be/MefabOA4q5c\ufeff", "time": "4 days ago", "author": "DIY Maker", "cid": "UgwA7TfE1MmyT2OFQ3t4AaABAg"}
{"text": "nice tyler\ufeff", "time": "4 days ago", "author": "DIY Maker", "cid": "UgwdvcqKOFU8Z776UFB4AaABAg"}
{"text": "Just wondering if you could mix like that and brush it on\ufeff", "time": "4 days ago", "author": "Martin Davis", "cid": "UgxKFEx-AB2Y94igtJ94AaABAg"}
{"text": "Probably but like I mentioned.....careful placement is important because if you overlap it makes the color darker.\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "UgxKFEx-AB2Y94igtJ94AaABAg.8c3tpbxtqgr8c4s3VWvrZO"}
{"text": "LOL @the out of date GED prep book everyone always keeps.  Some light reading for your guests.\ufeff", "time": "4 days ago", "author": "Trevor Even", "cid": "UgwDbt6MToz2FnJcUgx4AaABAg"}
{"text": "Great job Tyler, you have inspired me to build bunk beds for my two grandsons on your other video which I thought was fantastic. I really like this idea for temporary bed service for guests and your room is back to normal when they leave. \nGood stuff, love it.\nAl\ufeff", "time": "4 days ago", "author": "chipshot442", "cid": "UgzuTmkmAVK6SvjLwLB4AaABAg"}
{"text": "Use it and then hide it! Thanks for watching Al!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "UgzuTmkmAVK6SvjLwLB4AaABAg.8c3squx--qF8c4ryVEv14I"}
{"text": "Great build man. Nice, straight forward, cost effective. I really want to build a queen size Murphy at some point. Thanks for the inspiration and the tips!\ufeff", "time": "4 days ago", "author": "Chris Harpster", "cid": "Ugx_-Vo79FMHhzeZ1fN4AaABAg"}
{"text": "Thanks for watching Chris!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "Ugx_-Vo79FMHhzeZ1fN4AaABAg.8c3sJFw9nns8c4rw-6KHJ0"}
{"text": "Hi Tyler,  Great build.  Did you add any more coats of finish after the stain/finish mix first coat? or was the one coat enough?\ufeff", "time": "4 days ago", "author": "VirginiaWoodsmiths", "cid": "UgwpZxYkMIXGPo_PkX54AaABAg"}
{"text": "I sprayed two coats with the tint and a third clear coat over the top.\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "UgwpZxYkMIXGPo_PkX54AaABAg.8c3sDXCjWuO8c4rhTaavrn"}
{"text": "You had 2 mistakes, the second one was you didn't have a cap on in the room, but noticed you corrected that quickly. Nice build!\ufeff", "time": "4 days ago", "author": "Harki Dodia", "cid": "Ugzk9l6vbaLEYB9sLLB4AaABAg"}
{"text": "+Harki Dodia Lol! Happens when you forget it outside!! Thanks for watching!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "Ugzk9l6vbaLEYB9sLLB4AaABAg.8c3p1cOGTFf8c3qtf0jkv5"}
{"text": "Great video!  Just like most of them. Your channel is one I keep an eye on.\ufeff", "time": "4 days ago", "author": "rich hubert", "cid": "UgwKXAnF85Z6JGY_f8R4AaABAg"}
{"text": "+rich hubert Thanks for the support Rich!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "UgwKXAnF85Z6JGY_f8R4AaABAg.8c3fn3iBeqJ8c3qpM36Fal"}
{"text": "Great job Tyler! That looks fantastic. I especially like the idea of mixing the stain and clear coat. \nKeep up the great work \n\nThanks for sharing\ufeff", "time": "4 days ago", "author": "Roy Wrenn", "cid": "UgzsvGvGJFhtovSC8BJ4AaABAg"}
{"text": "+Roy Wrenn Saves a TON of time! Thanks for watching Roy!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "UgzsvGvGJFhtovSC8BJ4AaABAg.8c3bver-wiU8c3qmlWJNUE"}
{"text": "Cool solution. I know it doesn\u2019t have the spring to hold it upright like some of the kits, but it is not much harder to put a couple of bolts in like your design. Nice job!\ufeff", "time": "4 days ago", "author": "Bruce A. Ulrich", "cid": "UgzpUkRFBNKoAqpfzit4AaABAg"}
{"text": "+Bruce A. Ulrich Good to hear, Thanks for watching!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "UgzpUkRFBNKoAqpfzit4AaABAg.8c3Z_SpBPjc8c3qjpGjV7v"}
{"text": "Looks good!\ufeff", "time": "4 days ago", "author": "Mortgage & Mitre", "cid": "Ugyac5IAvBVglJWCMDt4AaABAg"}
{"text": "+Mortgage & Mitre Thanks for watching!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "Ugyac5IAvBVglJWCMDt4AaABAg.8c3Xveaojmu8c3qgr6Gf_9"}
{"text": "Nice build, Tyler!  It looks great!!\ufeff", "time": "4 days ago", "author": "KSFWG", "cid": "Ugwv2JDAp07f_xdp-Tp4AaABAg"}
{"text": "+KSFWG Thanks Dave!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "Ugwv2JDAp07f_xdp-Tp4AaABAg.8c3VJ0Vz-tL8c3qfkgpEDh"}
{"text": "Great project.  Another cheap option for coloring clear water-based finishes is just throw some instant coffee in it.  Did this a while back with a project covered in red oak plywood.  Thru a trial and error process, I found best trick was to dissolve a large amount of coffee crystals in a cup of hot water, then add this to the water poly.  Do a bit at a time as you can always darken it but  can't go back.  Made a great golden-oak finish, and subsequent coats darken the finish, but recoating can make for dark streaks in the corners, so once the desired color is achieved, additional finish coats should be clear coats.\ufeff", "time": "4 days ago", "author": "gjforeman", "cid": "UgyO-_O1HzmjGwB0w_J4AaABAg"}
{"text": "+gjforeman That sounds delicious! Thanks for the tip!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "UgyO-_O1HzmjGwB0w_J4AaABAg.8c3VHdE3l5Q8c3qeddn815"}
{"text": "Tyler G Not sure how it would taste, but if you're a coffee person it smells great while drying.\ufeff", "time": "4 days ago", "author": "gjforeman", "cid": "UgyO-_O1HzmjGwB0w_J4AaABAg.8c3VHdE3l5Q8c5RKVHTlyA"}
{"text": "Awesome job Tyler! \ud83d\udc4d\ud83d\udc4a\ufeff", "time": "4 days ago", "author": "Fred McIntyre", "cid": "UgwG-_H76ElZ6YeI-Hx4AaABAg"}
{"text": "+Fred McIntyre Thanks Fred!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "UgwG-_H76ElZ6YeI-Hx4AaABAg.8c3V-Oxrgik8c3qbm9KtKt"}
{"text": "Do the plans cover other sized mattresses? I'm about to build a murphy bed for a king size and would love to not spend so much $$ on the premade kits\ufeff", "time": "4 days ago", "author": "Brian Nelson", "cid": "UgwfFtYs-qZh1Y-NnDN4AaABAg"}
{"text": "Nice video Tyler! Thanks for sharing.\ud83d\ude0e\ud83d\udc4dJP\ufeff", "time": "4 days ago", "author": "Jp's Custom Woodworking", "cid": "UgyQf_HU9x8rbzSTynt4AaABAg"}
{"text": "+Jp's Custom Woodworking Thanks Jp!!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "UgyQf_HU9x8rbzSTynt4AaABAg.8c3S8hu4YHz8c3qZVmpyoE"}
{"text": "You're very welcome Tyler \ud83d\ude0e\ufeff", "time": "4 days ago", "author": "Jp's Custom Woodworking", "cid": "UgyQf_HU9x8rbzSTynt4AaABAg.8c3S8hu4YHz8c3zrryBpwT"}
{"text": "Isn\u2019t that a concept from DIY Creators ?\ufeff", "time": "4 days ago", "author": "Maxime Boissonneault", "cid": "Ugz9t0Fk017PTdHczxt4AaABAg"}
{"text": "+Maxime Boissonneault Similar hardware, different design.....although Murphy beds can't get that much different.\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "Ugz9t0Fk017PTdHczxt4AaABAg.8c3QYuFzWVu8c3qXcw_Xq7"}
{"text": "Thanks for the project.  It's a refreshing new design.\ufeff", "time": "4 days ago", "author": "Tim Bowman", "cid": "UgwPkVWYjitsQXYo2fF4AaABAg"}
{"text": "+Tim Bowman Thanks for watching!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "UgwPkVWYjitsQXYo2fF4AaABAg.8c3OeZchxpN8c3qSgH2f6Z"}
{"text": "Hey, Tyler. \u00a0I thought the shelves were overkill or unnecessary until I realized you built them to serve as the legs when the bed is down. \u00a0Nice design and great solution.\ufeff", "time": "4 days ago", "author": "Mike Dixon", "cid": "UgxMssrCqyO3unN-iBx4AaABAg"}
{"text": "+Mike Dixon Nice and sturdy this way. Thanks for watching!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "UgxMssrCqyO3unN-iBx4AaABAg.8c3MWdm2_Fo8c3qRV9gVh0"}
{"text": "Awesome Tyler, keepum comin !!!\ufeff", "time": "4 days ago", "author": "Mike Neuhaus", "cid": "UgywyMoyUrlw5zlcTBF4AaABAg"}
{"text": "+Mike Neuhaus Thanks Mike!!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "UgywyMoyUrlw5zlcTBF4AaABAg.8c3LNI3ktkg8c3qP-g0NYa"}
{"text": "Very nice!  Thanks for the video!\ufeff", "time": "4 days ago", "author": "Michael Coghill", "cid": "UgwO-5wyPxqMVa5KaMJ4AaABAg"}
{"text": "+Michael Coghill Thanks for watching!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "UgwO-5wyPxqMVa5KaMJ4AaABAg.8c3KHqT92AC8c3qNNCBufR"}
{"text": "EXCELLENT, SUPERB and PROFESSIONALLY Built my friend!! I certainly have the utmost respect for someone who does not edit out an \"overlook\". GREAT JOB and Video, Tyler.\ufeff", "time": "4 days ago", "author": "Orange Rocket", "cid": "Ugzbm-lz1VGQWuig1oZ4AaABAg"}
{"text": "+Orange Rocket Good to hear, Thanks for watching!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "Ugzbm-lz1VGQWuig1oZ4AaABAg.8c3K2Gmz5ho8c3qMG7qpPM"}
{"text": "I love the idea but my wife does not. I was thinking of building something like that for my sons room.\ufeff", "time": "4 days ago", "author": "Franks DIY", "cid": "UgzgCo7JUngItQ04h0R4AaABAg"}
{"text": "+Franks DIY A man.....gotta find a good negotiating point man!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "UgzgCo7JUngItQ04h0R4AaABAg.8c3JmL_O8Un8c3qJRDYIsI"}
{"text": "Nice job..My first table saw was a circular saw bolted from underneath. Now THAT made me nervous. :)\nThe little \"mistake\" didn't even show in the end, came out awesome..\ufeff", "time": "4 days ago", "author": "Path in AZ", "cid": "UgzMwDME6WmPjAS91Tp4AaABAg"}
{"text": "+Path in AZ That would be terrifying! Thanks for watching!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "UgzMwDME6WmPjAS91Tp4AaABAg.8c3ItoFDMBD8c3qFvVdZvx"}
{"text": "They call that the suicide saw for a reason.\ufeff", "time": "1 day ago", "author": "Phil'd With Malice", "cid": "UgzMwDME6WmPjAS91Tp4AaABAg.8c3ItoFDMBD8cBCdVLiiNm"}
{"text": "nice build Tyler.  Question...I am considering a murphy bed in our new home.  Do you think it is possible to mount a tv to the bed so that when it is folded up you can watch tv?  Thanks for any advice and thanks for making these videos.\ufeff", "time": "4 days ago", "author": "Garrett Welfare", "cid": "Ugz5Wpx5X2YpBfvT23h4AaABAg"}
{"text": "Garrett Welfare, due to window placement, my thought has been to build one that pivots on a long side, rather than the head. Allowing for a shorter cabinet that fits under my odd window. Might that be enough to hang a TV?\ufeff", "time": "4 days ago", "author": "Tonia Roberts", "cid": "Ugz5Wpx5X2YpBfvT23h4AaABAg.8c3IFS_8EPJ8c3RfJ7WtsD"}
{"text": "+Garrett Welfare I am not sure that the tv would be able to supports itself hanging from the back like that. Different forces compared to haging vertical. Can always test and see. Murphy bed won't care what's on there!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "Ugz5Wpx5X2YpBfvT23h4AaABAg.8c3IFS_8EPJ8c3qD8mn60u"}
{"text": "that was my concern too.  I know that the tv mounts have the hooks at the top, and the set screws at the bottom which keep it stable, but I am not sure if the vertical force when rotated 90 degrees is too much for the set screws to hold.  Thanks for your response and great videos.  I have learned a few tricks from them.\ufeff", "time": "4 days ago", "author": "Garrett Welfare", "cid": "Ugz5Wpx5X2YpBfvT23h4AaABAg.8c3IFS_8EPJ8c5MvvgxgZi"}
{"text": "Nice build! What is that I see, another one on the way? Congrats! Better build some more beds!\ufeff", "time": "4 days ago", "author": "Kyle Veatch", "cid": "UgxG_3UWThsDhMQ9GGJ4AaABAg"}
{"text": "+Kyle Veatch Sharp eye! Thanks, more bunk beds on the way!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "UgxG_3UWThsDhMQ9GGJ4AaABAg.8c3FAOtXSo28c3q2B_PzvM"}
{"text": "Nice job buddy.  But far away from professional woodworking  . Sorry bro\ufeff", "time": "4 days ago", "author": "hank iven", "cid": "UgwGj2W3Hqq5giIdtkx4AaABAg"}
{"text": "+hank iven Don't see your point. Never claim to be a pro...my brand is DIY.\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "UgwGj2W3Hqq5giIdtkx4AaABAg.8c3EMtfsZbQ8c3FZijUAox"}
{"text": "One cool upcoming woodworker at 4:06 and at 9:26 showing some great cleanup skills. Great project as always Ty, and that Fuji sprayer sure looked awsome. Is the overspray really so minimal that no covering is needed in the shop?\ufeff", "time": "4 days ago", "author": "Bellevue Woodshop", "cid": "Ugy2vaTYaOM_R6a7BmJ4AaABAg"}
{"text": "+Bellevue Woodshop It is if you go slow with a lower spray feed. But, shooting only a clear water based top coat I think the finish is dried by the time it lands on anything besides the project. Haven't noticed any Ill effects. Thanks for watching Roy, hope all had been well across the pond.\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "Ugy2vaTYaOM_R6a7BmJ4AaABAg.8c3EL8uyqvl8c3pzyRrvyV"}
{"text": "Muy Bueno el proyecto \nPara cuando tienes pocos espacios.\nFelicidades.\ufeff", "time": "4 days ago", "author": "Lorenzo Gonzalez", "cid": "UgybwAHg1uxVcN5Gml54AaABAg"}
{"text": "What? A youtube bed project not sponsored by Casper? Isn't that against the rules? (Looks great!)\ufeff", "time": "4 days ago", "author": "Toby Kathan", "cid": "Ugy1k3Y5zjiaYYUO4RJ4AaABAg"}
{"text": "+Toby Kathan lol! Not this time! Thanks for watching!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "Ugy1k3Y5zjiaYYUO4RJ4AaABAg.8c3D3OwT2K08c3po3lLsZq"}
{"text": "Maybe it's just my screen, but the white balance seems awfully high in this video.\ufeff", "time": "4 days ago", "author": "B.Gilly", "cid": "Ugxe9UqjOFmkQrnXQaR4AaABAg"}
{"text": "+B.Gilly When I jump from inside to out the shop seems very bright. No change in settings.\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "Ugxe9UqjOFmkQrnXQaR4AaABAg.8c3Ag7b2Z-m8c3plRwm90D"}
{"text": "Very nice build and what a great finishing..?\ufeff", "time": "4 days ago", "author": "Stamatis T", "cid": "UgxZ7Zmhq_SNksEq9zh4AaABAg"}
{"text": "+Stamatis T Thanks man, super pleased with the finish!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "UgxZ7Zmhq_SNksEq9zh4AaABAg.8c3A3WXmtEE8c3pgBoM4mo"}
{"text": "Great project, super build. Is the purpose of this bed to be in the guest room and not used often?\ufeff", "time": "4 days ago", "author": "Paulina Paulino", "cid": "UgyaLHazPMooF3Y4zJ54AaABAg"}
{"text": "+Paulina Paulino Yes, it will be used very rarely...3-4 times a year maybe. Thanks for watching!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "UgyaLHazPMooF3Y4zJ54AaABAg.8c39we4FiEo8c3pdIeS_j7"}
{"text": "Great Tyler \ud83d\udc4f\ud83d\udc4f\ud83d\udc4f\ud83d\udc4f\ud83d\udc4f\ud83d\udc4f\ufeff", "time": "4 days ago", "author": "giovanni petitti", "cid": "UgwuBg24wIGtDomGYq14AaABAg"}
{"text": "+giovanni petitti Thank you!!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "UgwuBg24wIGtDomGYq14AaABAg.8c39dURBDyf8c3pYoPyv50"}
{"text": "Great video Tyler\ufeff", "time": "5 days ago", "author": "Leo Braceday", "cid": "UgzqbMLPoxhlviIIrrF4AaABAg"}
{"text": "+Leo Braceday Thanks!\ufeff", "time": "4 days ago", "author": "Tyler G", "cid": "UgzqbMLPoxhlviIIrrF4AaABAg.8c382GB3uFp8c3pXG6-ln-"}
`

**Comment by d0tN3t** [comment]
Hey meagain69! It's a great script I agree! I've been working with it for some time now. You may be having some issue with the json format because the original programmer is using a 'new line delimiter' style of json. I had a hard time understanding it too but I've now come to love using it. 

What you want to do is load it into a list and then parse it out into a format that you are comfortable with.  

Here is a good example:

```
json_data = []
with open('batch_cc/RedHead/private/sbx-FFUNXXw.json')as fp:
    for i in fp:
        json_data.append(json.loads(i))
data = []

for i in json_data:
    data.append(i['Text'])
```

If you still need help, feel free to send me an email at jason.quintana1@gmail.com
I'm more than happy to help with any questions you may have.
