### ISSUE TITLE
Optimization Advice

### ISSUE THREAD

**Issue by elibroftw** [egbertbouman/youtube-comment-downloader#84]
https://github.com/egbertbouman/youtube-comment-downloader/blob/master/youtube_comment_downloader/downloader.py#L91

Instead of converting two generators into a list and then adding the lists, use `itertools.chain`
```py
# example
>>>a_list = [1, 2, 3]
>>>from itertools import chain
>>>b_list = [4, 5, 6]
>>>for item in chain(a_list, b_list):
>>>    print(item) 
1
2
3
4
5
6
```

And then for https://github.com/egbertbouman/youtube-comment-downloader/blob/master/youtube_comment_downloader/downloader.py#L81, we can avoid a double search by doing the below.
```py
# from contextlib import suppress
with suppress(StopIteration):
    raise RuntimeError('Error returned from server: ' + next(search_dict(response, 'externalErrorMessage')))
```

**Comment by egbertbouman** [comment]
I don't really see a need for this optimization, but did remove the double search.

**Comment by elibroftw** [comment]
It's fine these are changes I use in my own app, so I just wanted to let you know of them to contribute back.
