### ISSUE TITLE
Feature request: monitor for comment id

### ISSUE THREAD

**Issue by superbonaci** [egbertbouman/youtube-comment-downloader#85]
Hi, youtube is deleting lots of comments randomly. Would be possible to set a monitor feature for given comments?
Example comments from this video https://www.youtube.com/watch?v=qIQ3xNqkVC4:
````
$ youtube-comment-downloader --check UgyGGE7kdaa81wd0uf14AaABAg Ugx7hQmZzlDQa2baCPV4AaABAg Ugy9w8NUffGyeKcxOw14AaABAg
````
````
$ youtube-comment-downloader --youtubeid qIQ3xNqkVC4 --check UgyGGE7kdaa81wd0uf14AaABAg Ugx7hQmZzlDQa2baCPV4AaABAg Ugy9w8NUffGyeKcxOw14AaABAg
````
````
$ youtube-comment-downloader --check UgyGGE7kdaa81wd0uf14AaABAg Ugx7hQmZzlDQa2baCPV4AaABAg xxxxxxxxxxxxxx
xxxxxxxxxxxxxx is missing.
````
````
$ youtube-comment-downloader --youtubeid qIQ3xNqkVC4 --check UgyGGE7kdaa81wd0uf14AaABAg Ugx7hQmZzlDQa2baCPV4AaABAg xxxxxxxxxxxxxx
xxxxxxxxxxxxxx is missing from video qIQ3xNqkVC4.
````
Only mention anything if a comment is missing, otherwise be silent.

I don't know, if a comment is removed, a new one can be generated with same id by another user. That would a problem because would give a false positive.

**Comment by egbertbouman** [comment]
I don't think this is possible without downloading all comments again.

Perhaps you could look into using the official API to do this.
