### ISSUE TITLE
--youtubeid=-idwithdash -sLwIBEjb0E calls -s for sorting options

### ISSUE THREAD

**Issue by dfury0** [egbertbouman/youtube-comment-downloader#87]
It looks like a dashed address starting with '-s' calls the sort argument. Is there a way around this?  

command:
`youtube-comment-downloader -y=-idwithdash -sLwIBEjb0E -o -sLwIBEjb0E.json`

error:
`youtube-comment-downloader: error: argument --sort/-s: invalid int value: 'LwIBEjb0E'`

**Comment by egbertbouman** [comment]
If you execute the command like this, it should work:
`youtube-comment-downloader -y=-sLwIBEjb0E -o=-sLwIBEjb0E.json`
