### ISSUE TITLE
Limit to an amount of comments

### ISSUE THREAD

**Issue by apochoa999** [egbertbouman/youtube-comment-downloader#9]
The scrapper is great but I feel it lacks the ability to take in a number representing the MAX amount of comments it should extract. I believe this is something not too difficult to implement and would be very useful since some videos can have thousands of comments and the extraction takes too long. 

Thanks and keep up the good work!

**Comment by egbertbouman** [comment]
Thanks for the suggestion! I just implemented this in https://github.com/egbertbouman/youtube-comment-downloader/commit/9572fde45d4791560bf96d7817b4e21fbf67485e.
