### ISSUE TITLE
[Feature request] Add support for Odysee

### ISSUE THREAD

**Issue by superbonaci** [egbertbouman/youtube-comment-downloader#92]
Request to add support to download comments from https://odysee.com/

**Comment by superbonaci** [comment]
do not stale.

**Comment by superbonaci** [comment]
do not stale.

**Comment by superbonaci** [comment]
do not stale

**Comment by superbonaci** [comment]
do not stale

**Comment by superbonaci** [comment]
do not stale

**Comment by biggestsonicfan** [comment]
A fork of `youtube-comment-downloader` with modification for Odysee might be possible, but the module itself uses Youtube's API, which I can only assume Odysee does not use. A fork of it's own, `odysee-comment-downloader` might be appropriate, however I feel this is out of scope for this project.

**Comment by superbonaci** [comment]
Then I'll close this.
