### ISSUE TITLE
RuntimeError: Failed to set sorting

### ISSUE THREAD

**Issue by jonlee112** [egbertbouman/youtube-comment-downloader#93]
Hi there, just making you aware of an error I am getting when running the following code to download the comments of multiple youtube video ids:

```
with open('youtube_ids.csv', 'r') as fp:
    youtube_ids = fp.readlines()

with io.open('youtube_comments.txt', 'a', encoding='utf8') as fp:
  for youtube_id in youtube_ids:
      print('Downloading', youtube_id)
      for comment in download_comments(youtube_id):
        comment['video_id'] = youtube_id
        comment_json = json.dumps(comment, ensure_ascii=False)
        print(comment_json.decode('utf-8') if isinstance(comment_json, bytes) else comment_json, file=fp)

```

It generally downloads the comments of some number of videos and then hits this error, stopping the downloads. So far, I think I simply restart the process deleting the youtube ids that have already been downloaded. But it's certainly a strange error to be getting. Re-running the youtube_id during which the error occurred works just fine upon restarting.

**Comment by jonlee112** [comment]
FYI, it 'may' be because it has just hit a video for which comments were turned off...but not sure. Will keep an eye on this pattern.

**Comment by egbertbouman** [comment]
I've managed to reproduce the problem, although it only seems to happen occasionally. Considering that comments do seem to download on a second attempt, I think it's likely an issue of making too many requests.

Perhaps you can try catching the `RuntimeError` and re-trying to download the comments after sleeping for a number of seconds. You should propably also consider adding a sleep in between `download_comment` calls.

**Comment by qkum** [comment]
You could try download the comments first and run the sorting function/code on the comments/data after.

So your downloading does not stop in the middle of it all, so you have to start all over I imagine, to make sure you get them all.

Errors while sorting/cleaning the data after downloaded won't make you lose data.

**Comment by egbertbouman** [comment]
Closing this issue in favor of https://github.com/egbertbouman/youtube-comment-downloader/issues/105, this that one has a little more information.
