### ISSUE TITLE
Packaging as python dependency

### ISSUE THREAD

**Issue by lalitpagaria** [egbertbouman/youtube-comment-downloader#96]
Dear maintainer,

Thank you for the awesome repo.

Recently I have integrated code from this repo to [Obsei](https://github.com/obsei/obsei).
I am sorry to copy the code and use it instead of adding dependency as I wanted to modify the code a bit.
Please refer modified code (It have full attribution as well: [code file](https://github.com/obsei/obsei/blob/master/obsei/misc/youtube_reviews_scrapper.py) and [attribution file](https://github.com/obsei/obsei/blob/master/ATTRIBUTION.md)
Ideally, I like to use it as a dependency for proper integration please let me know if there is some chance to have this awesome lib providing data class to fetch comments.

See actual demo gif -
![obsei_youtube_demo](https://user-images.githubusercontent.com/19303690/153289685-30bb0dd1-c6f6-4946-be3e-287925301667.gif)

**Comment by egbertbouman** [comment]
I think it's a good idea to move the code into a class and put it on pypi. I'll work on this when I have some time.

**Comment by egbertbouman** [comment]
I just put the code in a class and uploaded the package to PyPi. I did't add the `until_datetime` functionality that you're using, but I did add an additional `time_parsed` key to the comment dictionary.

Please let me know if this works for you.

**Comment by lalitpagaria** [comment]
Hey, @egbertbouman Thanks for working on it. I will check it out and let you know.
