### ISSUE TITLE
Captcha Issue

### ISSUE THREAD

**Issue by 46cv8** [egbertbouman/youtube-comment-downloader#99]
Hey Guys,

Is there any intention to add a provision for avoiding captchas with this tool?
Like providing a youtube login or cookie or something. 
Recently I've been unable to use the tool because all the pages I request using the come back with 429 captcha required pages.
I  tried completing one captcha from a privacy mode browser from my IP, but it didn't seem to help.
I'm guessing it needs a cookie for a session that has completed a captcha.

**Comment by elibroftw** [comment]
In my code I either use browser cookie 3 to get the YouTube cookies or I use proxies after 4 requests using the default ip.

**Comment by 46cv8** [comment]
Thanks for that tip! It got me a bit closer it's now getting some data back rather than a captcha unfortunately it keeps saying 0 comments when there are actually more than 0. I'll have to try and debug more later if I have time. I wonder if they changed something but are only deploying the updates regionally so it's still working for everyone else.

**Comment by bpnordin** [comment]
The actual youtube api give you a quota of 10,000 requests a day https://developers.google.com/youtube/v3/guides/quota_and_compliance_audits

you can see the costs for each service here: 
https://developers.google.com/youtube/v3/determine_quota_cost

They are pretty cheap for listing comments. With 100 comments per requests, you can get 1,000,000 comments a day with no captcha/proxies
